### ISSUE TITLE
built-in actions / add conditionally

### ISSUE THREAD

**Issue by macrozone** [amwmedia/plop#101]
Awesome project!

I am playing around with it at this point and i found this pattern that i want to solve:

- create index file if it does not exist
- update index file to import xxx from './xxx'

this works by using an `add` with `abortOnFail: false` following a `modify`
but it will always show an error (altough it will not abort). This is confusing for the user.

so is it possible to either

- suppress this error completly
- have a `when()` function on every action (similar to prompts)
- have a `addOrModify` action

**Comment by amwmedia** [comment]
I agree that there's a lot of benefit to having a globally handled `when()` attribute for actions (similar to prompts). Right now you can achieve this by [using a dynamic actions array](https://plopjs.com/documentation/#using-a-dynamic-actions-array) but that's more complicated than it needs to be.

**Comment by macrozone** [comment]
@amwmedia I currently used this:

```
const insertIf = (condition, ...elements) => (condition ? elements : []);

const actions = [
  // ...
    ...insertIf(
      !exists(file),
      {
        type: 'add',
        path: file,
        templateFile: 'templates/sagas/index.js'
      }
    ),
  // ...
  ];


```

but yeah, it could be easier though. Can i let this open?

**Comment by amwmedia** [comment]
Yes, we'll leave this open as a TODO :+1:

**Comment by macrozone** [comment]
see PR above for a part-solution

**Comment by amwmedia** [comment]
added in v2.0 I believe there's another issue open for the idea of adding a `when()` function for actions. so I'm going to close this one.

**Comment by jacksteamdev** [comment]
@amwmedia I haven't been able to find that other issue about conditional actions. Should we reopen this one?

**Comment by jozef-mikusinec-kiwicom** [comment]
For future googlers, there is now `skipIfExists`, so if you want to create a file if it does not exist and update an existing one if it does, one option is to create an empty file in one action (with `skipIfExists: true`) and then modify it in another action.

This is what I use:

```
  {
    type: 'add',
    path: 'src/modules/{{ path }}/{{ moduleName }}/index.ts',
    template: '',
    // We just need to ensure the file exists. In case it already does, just
    // silently go to the next action.
    skipIfExists: true,
  },
  {
    type: 'append',
    path: 'src/modules/{{ path }}/{{ moduleName }}/index.ts',
    separator: '',
    template:
      "export { default as {{ moduleName }}{{ pageName }} } from './pages/{{ pageName }}/{{ moduleName }}{{ pageName }}';\n",
  },
```
