### ISSUE TITLE
disable handlebar html escape

### ISSUE THREAD

**Issue by macrozone** [amwmedia/plop#104]
I ran into the following situation:

i did a generator for a reducer where you can define an initial state with its initial value,

e.g.

`theme: "default"`

a template for this might look like this:

`{{propertyName}}: {{initialValue}}`

Because initialValue could be anything (true, 42, "Rosebud", null, undefined), i probably would not put quotes in the template, so the user would need to pass the values with quotes if they are strings.

The problem is now, that handlebars will write html entities in the file if you pass quotes! 

Workaround is to use tripple brackets `{{{initialValue}}}` but its likely to forget that. While on webpages, escaping is a good default behaviour, its bad in code generators.

I think there is an option to disable escaping globally for handlebars and we should consider to do so

**Comment by amwmedia** [comment]
I see your point. However, I don't think it would be good to alter Handlebars' default rendering behavior by default in plop because I think that could cause even more confusion. People can use plop to generate all sorts of files, JS, HTML, CSS, etc. So, while this may seem counter-intuitive in some cases, in other cases it is entirely expected behavior.

**Comment by macrozone** [comment]
@amwmedia agree on that, but i believe that plop is far far more used to generate code than html ;-)

but yeah, this would be breaking so maybe we should have an option on a generator

**Comment by amwmedia** [comment]
I think this could go nicely with the work that is being proposed in #10. Another templateRenderer could easily be created called `handlebarsNoEscape`. Or a 3rd party handlebars templateRenderer could be `plop.load`ed and accept a handlebars config object.

**Comment by crutchcorn** [comment]
I just wanted to leave my thoughts. I completely agree with @amwmedia. Having different default behavior than what Handlebar's docs initially lay out is confusing and potentially harmful to the experience. I think that having a seperate template renderer is probably the most ideal workaround - allowing different functionality for those that need it

**Comment by macrozone** [comment]
I found another issue https://github.com/amwmedia/plop/issues/112

i believe that handlebars is the wrong tool for code generation. handlebars is made for html.

**Comment by crutchcorn** [comment]
Simply speaking for myself and not for the project:

Explain WHY handlebars is the wrong tool for code generation. There's nothing about it that's explicitly for HTML coding and even escaping has it's uses outside of HTML. I would suggest becoming more comfortable with the limitations and abilities handlebars has.

As a seperate idea - there is already work being done to allow for handlebars replacements (see https://github.com/amwmedia/plop/issues/104#issuecomment-362702547). It's now just a matter of waiting for the development process to see the feature become implamented
