### ISSUE TITLE
Use lastest (master version) of node-plop with CLI

### ISSUE THREAD

**Issue by ArTiSTiX** [amwmedia/plop#108]
I'm trying to use some earliest features of node-plop (append action, manually passing data to actions, ...), but i can't figure out how to install plop globally with the latest version of node-plop from master branch.

When are you planning to upgrade version though ?
Those new features are really useful, and i don't want to lose time waiting for it, or do a work-around to always be up-to-date (isn't it the goal of this awesome tool - save time ?)

Thanks for your excellent tool.

**Comment by amwmedia** [comment]
I'll try to get this published today. Sorry, I don't normally let things wait for so long... things got really busy for me. I'll at least get node-plop out there today

**Comment by amwmedia** [comment]
v0.13.0 is now on NPM

**Comment by ArTiSTiX** [comment]
@amwmedia Thanks, amazing !
