### ISSUE TITLE
handlebars removes certain strings with `false`

### ISSUE THREAD

**Issue by macrozone** [amwmedia/plop#112]
this is really weird. I have this template file:

```
{{actionName}}: (state, action) => ({
  ...state,
  {{{propertyName}}}: {{{propertyValue}}}
}),
```

e.g.

```
{
actionName: "showNavigation",
propertyName: "navigationVisible", 
propertyValue: "true"
}
```

it renders as expected:

```
showNavigation: (state, action) => ({
  ...state,
  navigationVisible: true
}),
```

but with 

```
{
actionName: "showNavigation",
propertyName: "navigationVisible", 
propertyValue: "false"
}
```

it renders 

```
showNavigation: (state, action) => ({
  ...state,
}),
```

it even removes `navigationVisible: ` (!)

any other value seems to work, including "null"

this is extremly weird and looks like there is some additonal processing in handlebars. any idea?

**Comment by macrozone** [comment]
workaround is to use the string `"Boolean(false)"`

**Comment by amwmedia** [comment]
I wasn't able to reproduce the issue described here on http://tryhandlebarsjs.com/. Are you able to?

**Comment by amwmedia** [comment]
@macrozone ?

**Comment by amwmedia** [comment]
I tried to reproduce this issue but was able to.
