### ISSUE TITLE
Modify destination file name/extension

### ISSUE THREAD

**Issue by gpmcadam** [amwmedia/plop#113]
I have a template that looks like this:

```
plop-templates/
  component/
    index.js.hbs
    Component.css.hbs
    Component.test.hbs
```

Two things I'd like to do with an `addMany`:

 1. Rename some of the destination files e.g. `Component.css.hbs` to `{{name}}.css`, but _not_ `index.js.hbs`
 2. Similar to the above, drop the `.hbs` extension for all destination files (leaving them with their proper extensions, in this case, `.js` or `.css`)

I have the following `addMany` configuration:

```
plop.setGenerator("component", {
    description: "create a component",
    prompts: [
      {
        type: "input",
        name: "name",
        message: "component name"
      }
    ],
    actions: [
      {
        type: "addMany",
        destination: "./src/components/{{name}}",
        base: `${templatesPath}/component/`,
        templateFiles: `${templatesPath}/component/*.hbs`
      }
    ]
  })
```

Is this not possible without a custom action?

**Comment by amwmedia** [comment]
point 1 can be achieved by using handlebar template values in the actual names of the template files. So in the component folder you would have the a file named `{{dashCase name}}.js`. point 2 is a little harder, there's no current way to rename the templates on their way to the destination folder. If you want the destination to have a `.js` file, the template will also need to be a `.js` file.

**Comment by youssefsharief** [comment]
@amwmedia  Can you please explain how to do this?
I used "{{dashCase name}}.component.html.hbs" as my component name. Sadly, it does not work.

**Comment by codytooker** [comment]
@youssefsharief Running into the same problem. Have you found the solution.   Plop simply errors saying `There isn't a valid template file for action #1`

**Comment by amwmedia** [comment]
@gpmcadam Sorry, I don't think I read this issue carefully enough and missed your meaning when I responded before. The functionality you are looking for should now be possible with the `stripExtensions` property of the [addMany](https://plopjs.com/documentation/#addmany) action. You can specify what extensions you would like to have stripped while the files are being processed. @youssefsharief and @codytooker please have a look and see if this helps you both.

**Comment by aneurysmjs** [comment]
> point 1 can be achieved by using handlebar template values in the actual names of the template files. So in the component folder you would have the a file named `{{dashCase name}}.js`. point 2 is a little harder, there's no current way to rename the templates on their way to the destination folder. If you want the destination to have a `.js` file, the template will also need to be a `.js` file.

yeah, can you give a concise example of that? the documentation is not that friendly for that case.


or maybe @youssefsharief already solved it? can you give me a hand?

**Comment by amwmedia** [comment]
So, if you have a folder structure like:
```
templates/
  {{dashCase name}}-test.js.hbs
src/
plopfile.js
```

And a plopfile like:
```javascript
module.exports = function (plop) {
  plop.setGenerator("test", {
    description: "create a component",
    prompts: [
      {
        type: "input",
        name: "name",
        message: "name"
      }
    ],
    actions: [
      {
        type: "addMany",
        destination: "src/tests/{{name}}-folder",
        base: `templates`,
        templateFiles: `templates/*.hbs`
      }
    ]
  })
};
```

running a command like:
```
plop test asdf
```

results in a new file at: `src/tests/asdf-folder/asdf-test.js`

hope this helps

**Comment by aneurysmjs** [comment]
jaja, that's what the last thing I've tried and that's it ))) .

thanks for your reply,it's just that in the documentation is not easy to get it at first

**Comment by amwmedia** [comment]
If you have ideas on how to improve the docs, please feel free to submit a PR 👍

**Comment by amwmedia** [comment]
Doc PRs made to plopjs/plop will be replicated to plopjs.com.

**Comment by aneurysmjs** [comment]
> So, if you have a folder structure like:
> 
> ```
> templates/
>   {{dashCase name}}-test.js.hbs
> src/
> plopfile.js
> ```
> 
> And a plopfile like:
> 
> ```js
> module.exports = function (plop) {
>   plop.setGenerator("test", {
>     description: "create a component",
>     prompts: [
>       {
>         type: "input",
>         name: "name",
>         message: "name"
>       }
>     ],
>     actions: [
>       {
>         type: "addMany",
>         destination: "src/tests/{{name}}-folder",
>         base: `templates`,
>         templateFiles: `templates/*.hbs`
>       }
>     ]
>   })
> };
> ```
> 
> running a command like:
> 
> ```
> plop test asdf
> ```
> 
> results in a new file at: `src/tests/asdf-folder/asdf-test.js`
> 
> hope this helps

that's what we expect in the docs :) ....let me see what can I do ok? there's an amazing tool and should be more friendly.

have a nice day
