### ISSUE TITLE
plop command not found

### ISSUE THREAD

**Issue by forthrightstl** [amwmedia/plop#115]
Installing on a Mac, the `.bash_profile` isn't getting updated.  Looking in the code, there's no binary to run.

What should a plop alias point to?

**Comment by amwmedia** [comment]
Are you installing via npm?

**Comment by forthrightstl** [comment]
Yessir.

I was able to get it working by pointing to /src/plop.js.

Not sure what the more appropriate approach would be.

**Comment by amwmedia** [comment]
Strange. Yes, that's the entry point for the code, but it's weird that `npm install -g plop` didn't take care of it for you

**Comment by Skylnt** [comment]
npm install -g plop . working for me. thanks.

**Comment by ashish-gawali-adi** [comment]
How to tackle this is if I don't want to install plop globally? If I install it locally and have control over the environment in which the command will run, which location should I add or which file should I add to the environment? Is it `/node_modules/plop/bin/` or `/node_modules/plop/bin/plop.js`

**Comment by amwmedia** [comment]
Probably the easiest thing to do is to install via NPM and then run it via an NPM task like `npm run generate` then in your package.json you would add "generate": "plop" to your list of tasks.

**Comment by ashish-gawali-adi** [comment]
Oh ohk, I will try this out! At this point to tackle it, I added the `.bin` folder to `PATH` in the environment of my command window.

**Comment by amwmedia** [comment]
That should work too! But using the npm script doesn't require any additional steps if you need to work on the codebase on a new machine, so I've seen a lot of other projects go that route. Whatever works for you 👍🏻

**Comment by ashish-gawali-adi** [comment]
I was wondering if `node-plop` has a dependency on `node.js`, if I were to run a `plop` command on a system will it pick the `node` from the node.js install? And, if I were to use `node-plop` where will it pick the `node` command from?
