### ISSUE TITLE
Expected version ">=8.9.4"

### ISSUE THREAD

**Issue by fedulovivan** [amwmedia/plop#120]
Hi, there!
Come here on my way to find some lightweight alternative for yeoman, and your project looks quite suitable for this.
No offense, but what is a real reason to depend on a node above v8.9.4? Sorry if this information is already given somewhere.

![oldversion](https://user-images.githubusercontent.com/752105/42446831-6455b872-8380-11e8-8fdb-70c06f2093ab.png)

**Comment by amwmedia** [comment]
plop version 1.x supported node 4.0 and greater but one of plop's main dependencies (inquirer.js) dropped node 4 support and went to node 6. When that happened, I decided to make plop depend on what was (at the time) the current LTS version of node. That's how plop 2.x came to require node 8.9.4 :slightly_smiling_face:. 

Is the dependency on 8.x a problem for you? plop should (in theory) work fine on 6+.

**Comment by fedulovivan** [comment]
Thanks for quick reply! Our project is "quite conservative", so we were ought to use node 8.3.0 until recent time. So namely this version was set as default one on our development environment. As a consequence attempt to install plop was failed. 

So it might be better to depend on more older version, to prevent such issues for some users. 

But, btw, thanks to this issue we arranged some time and upgraded to 8.11.3:)
