### ISSUE TITLE
Executable files as template

### ISSUE THREAD

**Issue by williamdclt** [amwmedia/plop#129]
I'm trying to use Plop to generate projects, containing executable files (eg python scripts). When running Plop, the output files do not have the "executable" permission.

So I have a few questions:
- Is it a bug or a feature?
- Would a PR be welcome?
- If so, any hint on where that should be handled?

Cheers!

**Comment by amwmedia** [comment]
I'm not sure if this is something that plop should handle automatically for security reasons. You should, however, be able to build it into your generator using a [custom action function](https://plopjs.com/documentation/#custom-action-function-) and the [fs.chmod](https://nodejs.org/api/fs.html#fs_fs_chmod_path_mode_callback) function.

**Comment by williamdclt** [comment]
I'm far from being an expert on security matters, but I don't see what kind of security issue could happen, do you have an example?

A custom action is a good idea, but this action would have to re-implement the whole logic of `addMany`  and add the "keep the executable flag" logic. I'll try and find an alternative

Thank you for the pointer to `fs.chmod`, will definitely be useful :)

**Comment by amwmedia** [comment]
you could use the `add` or `addMany` to generate the file and a customAction to change the permissions.

The more I think about this, the less I'm concerned about the security aspect. I suppose if the template has execute permissions, it would be logical the those permissions would be transferred to the generated files as well. 🤔

**Comment by amwmedia** [comment]
released in version 2.2.0
