### ISSUE TITLE
Cannot share ActionType between modules

### ISSUE THREAD

**Issue by r3dlin3** [amwmedia/plop#130]
Hi,

I have beginning to split different generators in different files for maintainability.
Is there a way to share an action type?

For instance, I have the following `plopfile.js`:
```
 plop.setActionType('myactiontype', function (answers, config, plop) {
        // do something
    });
plop.load('./myfile.js');
```

inside myfile.js:
```
module.exports = function (plop) {
plop.setGenerator('DataLakeStore', {
    description: 'This module generates ARM template file for a Data Lake Store',
    prompts: [...],
    actions: [
        ...
        {
            type: "myactiontype"
        }
});
}
```

It generates an error:
```
[FAILED] myactiontype Invalid action (#3)
```

**Comment by amwmedia** [comment]
Yes, you can share custom actions using [`plop.load()`](https://github.com/amwmedia/plop/blob/master/plop-load.md). In your example, are you trying to "push" the actions into the plopfile with the load method? If so, that's your problem. plop.load will "pull" assets into the current plopfile.

### example
`actionTypes.js`
``` javascript
module.exports = function (plop) {
    plop.setActionType('myactiontype', function (answers, config, plop) {
        // do something
    });
    plop.setDefaultInclude({ actionTypes: true });
}
```

`plopfile.js`
``` javascript
module.exports = function (plop) {
    plop.load('./actionTypes.js');
    plop.setGenerator('DataLakeStore', {
        ...,
        actions: [{
            type: "myactiontype",
            ...
        }]
    });
}
```

**Comment by r3dlin3** [comment]
Thanks for your answer. I have ended up with the following files so I can share `myactiontype` among my loaded generators:

`actionTypes.js`
```
module.exports = function (plop) {
    plop.setActionType('myactiontype', function (answers, config, plop) {
        // do something
    });
    plop.setDefaultInclude({ actionTypes: true });
}
```
`myfile.js:`
```
module.exports = function (plop) {
plop.load('actionTypes.js');
plop.setGenerator('MyGenerator', {
    description: '...',
    prompts: [...],
    actions: [
        ...
        {
            type: "myactiontype"
        }
});
}
```

`plopfile.js`

```
plop.load('./myfile.js');
```

Does it seem fine?

**Comment by amwmedia** [comment]
I think that seems logical. It certainly makes your plopfile lightweight!

**Comment by amwmedia** [comment]
you also have the option of deploying your actionTypes and/or generators to npm and loading them into multiple projects.
