### ISSUE TITLE
How to implement `autocomplete` feature to `PLOP`?

### ISSUE THREAD

**Issue by nuri-engin** [amwmedia/plop#131]
Hi there;

There is a `Autocomplete` `prompt` for `inquirer`. How can I implement this feature to `plop` itself?
And could you please give an example on here or documentation for implementing `autocomplete` feature?

Thanks in advance. @amwmedia 

Here is repostiory: https://github.com/mokkabonna/inquirer-autocomplete-prompt

**Comment by amwmedia** [comment]
You should be able to do this using the [`plop.setPrompt()` method](https://plopjs.com/documentation/#setprompt). This works just like the `registerPrompt()` method that's built into inquirer.

**Comment by nuri-engin** [comment]
Here I've tried to set `autocomplete` feature with `setPrompt` but couldn't be success!

I've installed `inquirer-autocomplete-prompt` with this `npm` command: 
`npm install -g --save inquirer-autocomplete-prompt` and the package locates under `node-modules` folder. 

Then refactored `plopfile.js` as;

```
let navMenuItems = ['Foo', 'Bar', 'Zet'];
const autoComp = require('inquirer-autocomplete-prompt');

module.exports = function(plop){
    plop.setPrompt('autocomplete', autoComp);
    plop.setGenerator('new-submodule', {
        description: 'Submodule Addition',
        prompts: [
            {
              type: 'autocomplete',
              name: 'autocomp',
              message: 'Hey Auto!',
              source: navMenuItems
            },

```
but it gives this error when I choose the `generator`: 
```
? [PLOP] Please choose a generator. new-submodule - Submodule Addition
> [ERROR] self.opt.source is not a function
```

What I'm missing here? Thanks @amwmedia

**Comment by amwmedia** [comment]
Just judging from the error, it looks like the package wants `source` to be a function. Maybe take a closer look at the documentation to see what it is expecting.

**Comment by amwmedia** [comment]
just looked at the [documentation](https://github.com/mokkabonna/inquirer-autocomplete-prompt#options) for `source`. Looks like it needs to be a function that returns a promise.
