### ISSUE TITLE
addMany not passing data to templates

### ISSUE THREAD

**Issue by matthosch** [amwmedia/plop#139]
If I call `add`, passing path and templateFile, the data is passed into the handlebars templates. However, if I call `addMany` the handlebars templates are rendered empty, even specifically passing in a data object. [Example gist](https://gist.github.com/matthosch/4365925351537c68fdc0595c415581ca
).

**Comment by matthosch** [comment]
Found and resolved issue, not passing correct data reference in template.

**Comment by youssefsharief** [comment]
I think this is still an issue for me

**Comment by ArchiCroc** [comment]
@youssefsharief  Do you happen to be running Plop on Windows? I just submitted a PR to node-plop to fix a couple issues I was having on windows with addMany. https://github.com/amwmedia/node-plop/pull/127
