### ISSUE TITLE
Is it possible to modify "data"?

### ISSUE THREAD

**Issue by brock** [amwmedia/plop#14]
Is it possible to modify the `data` or `answers` object after prompts?

Here is the general idea:

* A generator asks the user to select one of the Mongoose Schema models from the directory - this part works.
* I require the schema, then parse out the schema paths - this also works.
* I'd like to modify the `data` object that is passed to my jade templates so that I can do something like: `for each schema type, add an input field to the view`.

**Comment by amwmedia** [comment]
yes, this can be accomplished via an [custom action function](https://github.com/amwmedia/plop#custom-action-function). this would allow you to execute logic that could add additional properties to the answers object before your other actions happen.

**Comment by brock** [comment]
Many thanks - that did the trick!

**Comment by prbaron** [comment]
is it possible to do it in the prompt ?

For example, I would like the user to be able to create a directory and the file names can either have the directory name or another one. 

here is what I would like to do 
1. ask for the directory path  -> "where do you want to place the component ? (ex:foo/bar)"
2. ask for the file names -> "What is the comoponent name ?"

and in the 2. I would like to be able to have a predefined value of "bar"

**Comment by prbaron** [comment]
found it, you have to use [default](https://www.npmjs.com/package/inquirer) and you can have access to already defined answers.

**Comment by amwmedia** [comment]
good find 👍
