### ISSUE TITLE
[Documentation] Enquirer prompt types not obvious

### ISSUE THREAD

**Issue by yannvr** [amwmedia/plop#141]
It took me ages before realising Enquirer prompt types were supported out of the box because nothing in the documentation mentions it.
I think this is one of the first thing users will need help with when using plop.

I'm happy to help providing examples or amending the README. I think users should be aware of prompt types as listed on https://github.com/SBoudrias/Inquirer.js/#prompt

Do you agree?

Great job btw. Loving the tool! :)

**Comment by amwmedia** [comment]
I think it might make a lot of sense to have a section of the documentation for "Prompts" that explains that inquirer is used to handle the prompts and a link over to the inquirer documentation for question types. I'd prefer not to duplicate the documentation, but rather explain the linkage. 

Thoughts?

**Comment by gregglind** [comment]
+1 for even a link to that doc.  

All prompt types are described at Inquirer.

**Comment by yannvr** [comment]
I agree Andrew. A link and a general description about the available input
types would do. I'd say very early in readme before API details

On 16 Oct 2018 18:51, "Gregg Lind" <notifications@github.com> wrote:

+1 for even a link to that doc.

All prompt types are described at Inquirer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amwmedia/plop/issues/141#issuecomment-430333030>, or mute
the thread

**Comment by jonschlinkert** [comment]
Fwiw, just wanted to mention that [Enquirer v2.0 was released](https://github.com/enquirer/enquirer/) after this issue was created. It was a complete refactor from the ground up.

**Comment by yannvr** [comment]
+1 for integrating that sexy Enquirer 2.0 then :)

Yann

**Comment by amwmedia** [comment]
docs update [is live](https://plopjs.com/documentation/#using-prompts)
