### ISSUE TITLE
Having generators in separate files for logic dissection. 

### ISSUE THREAD

**Issue by Ashwin-Shenoy-NITK** [amwmedia/plop#150]
Is it possible for creating generators in separate files and then exporting them to the plopfile.js rather than having all the generators in a single plopfile.js ?

**Comment by FPierre** [comment]
plop/generators/database.js

```js
module.exports = (plop) => {
  plop.setGenerator('Database', {
    description: 'add database drivers and configuration files',
    prompts: [],
    actions: [],
  });
};
```

plop/generators/index.js

```js
module.exports = (plop) => {
  require('./database')(plop);
};
```

plopfile.js

```js
const setGenerators = require('./plop/generators');

module.exports = (plop) => {
  setGenerators(plop);

  // ...
};
```

This kind of separation?

**Comment by Ashwin-Shenoy-NITK** [comment]
Yes. Thank you for an example. Also it would be better to have a irc/gitter channel for implementation/example codes rather than having to fill out an issue all the time. The documentation is also lacking in some aspects regarding code examples so it's a bit tricky to follow.

**Comment by amwfl** [comment]
we do have a slack team available.

**Comment by Ashwin-Shenoy-NITK** [comment]
Is it open for public ?

**Comment by amwfl** [comment]
go here for an invite: https://plopjs-slack-vbeawnrrtk.now.sh/
