### ISSUE TITLE
Previous values not passed to validate function when bypassing

### ISSUE THREAD

**Issue by TimoGlastra** [amwmedia/plop#152]
When bypassing the inquirer prompt via the command line, the prompt  validation function is not getting the previous values anymore.

Passing the argument for the first prompt works fine, but when also passing the second prompt answer I get this error:
```
The "packageName" prompt did not recognize "heading-standard-v2" as a valid input value (ERROR: Cannot destructure property `elementType` of 'undefined' or 'null'.)
```

script:
```
plop --plopfile packages/element-generator/src/index.js Element -- --elementType component --packageName "heading-standard-v2"
```

```js
 const prompts = [
 {
    type: 'list',
    name: 'elementType',
    choices: [
      { name: 'Component', value: 'component' },
      { name: 'Section', value: 'section' }
    ]
  },
  {
    type: 'input',
    name: 'packageName',
    validate: (value, { elementType }) => {
        // validation function that relies on elementType answer from first prompt
    }
  }
]
```

**Comment by amwmedia** [comment]
did this work in a previous version of plop? if so, what was the last version that you know was working?

**Comment by TimoGlastra** [comment]
I think i did something wrong on my end. I reproduced my issue as described above but now it worked. Sorry for the bother.

**Comment by shawshankkumar** [comment]
Hey, I am running into the same issue. Can you share the code snipped which worked for you @TimoGlastra ? Thanks!
