### ISSUE TITLE
Using node_module package for templates

### ISSUE THREAD

**Issue by gurre** [amwmedia/plop#153]
I would like to build a general plop module that can be reused in several projects. Would it be possible to import templates from `node_modules` somehow?

E.g.

```
yarn add -D react-fun-plop
plop react-fun-plop component "my component" react
```

**Comment by amwmedia** [comment]
Yes, plop generators, helpers, actions, and partials can all be loaded via [`plop.load()`](https://github.com/amwmedia/plop/blob/master/plop-load.md). `plop.load()` was designed to be very simple for the consumer to use, in most cases the syntax should end up being `plop.load('module-name')`

If you want a basic example of a codebase that is designed to be loaded via `plop.load()`, check out [plop-pack-fancy-comments](https://github.com/amwmedia/plop-pack-fancy-comments)

hope this helps
