### ISSUE TITLE
Appending same file multiple times

### ISSUE THREAD

**Issue by M0nica** [amwmedia/plop#154]
Hi, I am trying to perform two `append` actions on my `index.js` file in my `plopfile.js`.  The first `append` works as expected when the second isn't present but when the second action is added then only the section `append` action works. Any suggestions as to how to have two seperate append actions for the same file?

https://github.com/M0nica/generate-kawaii-components/blob/5d47b3dce1c8bbb5eea3f107f336f514d0845fff/plopfile.js#L78

**Comment by amwmedia** [comment]
hmmm, I would think that would work. I'll try to look into it and report back.

**Comment by M0nica** [comment]
I think the issue was related to the RegEx I was using not properly handling a semi-colon. Append seems to be working as expected so I am going to close this issue.

**Comment by amwmedia** [comment]
thanks for the update 👍🏻
