### ISSUE TITLE
modify action with regex: $ matches end of file, not end of line

### ISSUE THREAD

**Issue by fluffynuts** [amwmedia/plop#155]
I have a modifier action which I've just spent a bit of time trying to figure out. Basically, I'd like to add a key & value to a typescript file like:

```typescript
export const Moo = {
	Key: "value",
	AnotherKey: "another value"
};
```

where `AnotherKey` may, or may not have a trailing comma after the value, depending on the existing code on disk. Obviously, if I'd like to add another key/value pair, I'd need to add a comma if it isn't there, so I should expect to be able to add to the below as well:

```
export const Moo = {
	Key: "value",
	AnotherKey: "another value",
};
```

Naturally, I can have a modifier to add in the key/value based on a regex match for `/};/`, and I would expect to be able to have a modifier before that which matches on `/"$/g` to replace with `","`. However the modifier only works if I set the pattern to `/"\n/g` -- as I discovered after simply setting the modifier to `/$/` and seeing my output appended to the end of the file.

This is a little counter-intuitive; I also expect that `^` is going to surprise me too. One could rather use the standard `\A` and `\Z` for start and end of file, or, if that is unavoidable, at least document that `^` and `$` apply to the entire file, as it's obviously not being treated as a bunch of lines, but rather as one giant swath of text.

**Comment by amwmedia** [comment]
Yes, the match is happening against the entire file as one block of text. Was there something in the docs that would make you believe that the file would be chunked up by lines?

The way I will normally do what you are attempting here is by putting a comment in at the spot where new data should be inserted. so...


```javascript
export const Moo = {
    Key: "value",
    AnotherKey: "another value",
	// new generated values here
};
```

This makes your regex a little simpler. Depending on your use-case, this might not be an ideal solution.

**Comment by fluffynuts** [comment]
Hi, again, missed prior notifications :/

Nothing in the docs, per se, would have led me to believe that regex evaluation would be line-based -- my expectation was entirely from using regex in other places, eg from sh/bash/zsh, which doesn't necessarily make it legitimate. Indeed, investigating blocks of lines of text against JS `.match` shows that my expectations were invalid. It was just surprising, I guess. Thanks for looking into this (:
