### ISSUE TITLE
path not found when has windows path delimiters

### ISSUE THREAD

**Issue by fluffynuts** [amwmedia/plop#156]
Whilst setting up an action to modify a file, I thought I'd do the "proper" cross-platform thing and use `path.join` for file paths. However, I kept on getting the message "File does not exists" (sic).

1. It would be nice if the message mentioned the path which was failing -- I added this debug info into `node-plop` locally to debug.

I found that my path that I'm providing is something like:
```
C:\\code\\project\\src\\components\\{{where}}\\index.ts
```
where `where` is an input parameter. However, when it gets to `modify.js`, the code there is looking for the file:
```
C:\\code\\project\\src\\components{{where}}\\index.ts
```
1. the variable `where` hasn't been substituted
2. probably related: the `\\` which should have been afte `components` has gone missing

I can work around this by, instead of using `path.join`, doing:
```
path: [ __dirname, "src", "components", "{{where}}", "index.ts" ].join("/")
```

I know that relative paths can also be resolved for me, but:
1. I like to use explicit paths
2. I'm actually storing and re-using the components base path ("C:/code/project/src/components"), so even if I weren't using __dirname, I'd still want to do some kind of concatenation, and I'd expect to be able to use platform-specific `path.join`.

**Comment by amwmedia** [comment]
I think the core of the problem here is that handlebars treats `\{{token}}` as an escaped token. Meaning that you did not want handlebars to process this as template data. 

I'd need to know more about you specific use-case to suggest a fix.

**Comment by fluffynuts** [comment]
Hey, sorry, only seen your response now -- I'm not sure what's up with GH notifications for me :/ However, what you say makes sense. I can work around the issue by using `/` instead of path.join, but it's great to know the _why_ of the problem. Thanks for taking the time to explain.
