### ISSUE TITLE
Rename File Action

### ISSUE THREAD

**Issue by DerekSeverson** [amwmedia/plop#160]
**First**, I love this module, great work! 

**Second**, I know there have been several _similar_ feature/issues created around what I'm about to ask - basically file renaming and hidden/dot files.  Here's a few of them: #33, #113, #114, #138, etc.  

But, my main issue is that I don't want hidden/dot files (ex: .gitignore, .npmrc, .babelrc, .eslintrc, .gitlab-ci.yml, etc.) in my templates folder because they actually change how my repository functions in that directory.  

Here's some examples: 
1. My `templates/.eslintrc` file now causes many of my javascript files in my templates directory to have linting errors because they have handlebars syntax for injecting data. 
2. My `templates/.gitignore` file now ignores some of the template files that I actually don't want ignored any more. 

I wrote a custom `renameMany` action, which I just have locally in my generator repository.  But, it seems like others may be running into this issue too.  Not only that, but the renaming action could be used for things other than just hidden/dot files.  

Below is my code for anyone who wants to use it and doesn't want to write it themselves:  
```js
// actions/rename-many.js

const path = require('path')
const util = require('util')
const fs = require('fs')
const globby = require('globby')

const renameAsync = util.promisify(fs.rename)

module.exports = async function renameMany (data, userConfig, plop) {
  // shallow-merge default config and input config
  const cfg = Object.assign({
    verbose: true
  }, userConfig)

  if (typeof cfg.renamer !== 'function') {
    throw new Error('Invalid "renamer" argument - must be a function')
  }

  if (typeof cfg.templateFiles === 'function') {
    cfg.templateFiles = cfg.templateFiles()
  }

  cfg.templateFiles = []
    .concat(cfg.templateFiles) // Ensure `cfg.templateFiles` is an array, even if a string is passed.
    .map(file => plop.renderString(file, data)) // render the paths as hbs templates

  const templateFiles = globby.sync(cfg.templateFiles, {
    nobrace: true
  })

  const filesRenamed = []
  for (let filepath of templateFiles) {
    const oldFileName = path.basename(filepath)
    const newFileName = cfg.renamer(oldFileName)
    const directory = path.dirname(filepath)
    const newFilepath = path.resolve(directory, newFileName)
    if (typeof newFileName === 'string') {
      await renameAsync(filepath, newFilepath)
      filesRenamed.push(path.relative(process.cwd(), newFilepath))
    }
  }

  const summary = `${filesRenamed.length} files renamed`
  if (!cfg.verbose) return summary
  else return `${summary}\n -> ${filesRenamed.join('\n -> ')}`
}
```

```js
// plopfile.js

module.exports = (plop) => {
  plop.setActionType('renameMany', require('./actions/rename-many'))
  plop.setGenerator('my-generator', {
    description: 'My Generator',
    prompts: [{
      type: 'input',
      name: 'appName',
      message: 'Application Name'
    }],
    actions: [
      {
        type: 'addMany',
        destination: process.cwd(),
        templateFiles: './templates/**/*',
        globOptions: { dot: true },
        base: './templates',
        force: true
      },
      /** 
        NOTE: finds files that start with an underscore (ex: `_eslintrc`) 
        and renames them to be dot/hidden files (ex: `.eslintrc`)
      */
      {
        type: 'renameMany',
        templateFiles: `${process.cwd()}/**/_*`,
        renamer: name => `.${name.slice(1)}`
      }
    ]
  })
}
```

--- 

**Lastly**, if you see value in it, my suggestion would be for a `rename` and/or `renameMany` action to be supported as a "native" plop action rather than users having to write it themselves as custom actions.  Please feel free to use my code above as a jumping off point (note: I used the addMany action source code as a resource for how to write this one).  Documentation around how one might handle dot/hidden files might be helpful as well.  

Thanks!!

**Comment by kenotron** [comment]
I, too, would need this functionality - though I would be happy to use this through a plop.load() just as well.

**Comment by amwmedia** [comment]
Sorry for the long wait. I believe functionality you are looking for should be possible through the `stripExtensions` property of the [`addMany`](https://plopjs.com/documentation/#addmany) action. However, I'm sure there is additional value that the code you wrote brings to plop. I would recommend you release it as an npm module so others can use it in their plopfiles via [`plop.load()`](https://github.com/amwmedia/plop/blob/master/plop-load.md)

**Comment by DerekSeverson** [comment]
Published to npm as [`plop-pack-rename-many`](https://www.npmjs.com/package/plop-pack-rename-many)!

**Comment by airtonix** [comment]
> ```js
>         globOptions: { dot: true },
> ```



> But, my main issue is that I don't want hidden/dot files (ex: .gitignore, .npmrc, .babelrc, .eslintrc, .gitlab-ci.yml, etc.) in my templates folder because they actually change how my repository functions in that directory.

No extra plugin required, just do this: 

```sh
> tree pkg/tools/generator-tool  -a
pkg/tools/generator-tool
├── .eslintrc.json
├── jest.config.ts
├── node_modules
├── package.json
├── src
│   ├── constants.ts
│   ├── files
│   │   ├── .eslintrc.json.t
│   │   ├── jest.config.ts
│   │   ├── package.json.t
│   │   ├── src
│   │   │   ├── constants.ts
│   │   │   ├── index.ts.t
│   │   │   └── {{ pascalCase name }}.ts.t
│   │   ├── tsconfig.base.json
│   │   ├── tsconfig.json
│   │   ├── tsconfig.lib.json
│   │   └── tsconfig.spec.json
│   ├── index.ts
│   └── ToolPackageGenerator.ts
├── tsconfig.base.json
├── tsconfig.json
├── tsconfig.lib.json
└── tsconfig.spec.json

5 directories, 20 files
```

Then like @amwmedia says, `stripExtensions` 

```ts
export function ToolPackageGenerator(plop: NodePlopAPI) {
  const reporoot = plop.getDestBasePath();
  const targetPackagesRoot = path.join(reporoot, "pkg", "tools");
  
  plop.setGenerator(name, {
    description,
    prompts: [
      {
        name: "name",
        message: "Package name",

        async validate(input: string) {
          const exists = await glob(input, { cwd: targetPackagesRoot });
          return !exists || exists.length <= 0;
        },
      },
    ],
    actions(answers) {
      if (!answers) return [];

      return [
        {
          type: "addMany",
          stripExtensions: ["t"],
          base: filesRoot,
          templateFiles: files,
          globOptions: { dot: true },
          destination: path.join(targetPackagesRoot, answers["name"]),
        },
        AddToRootPackageJson(plop, 'tools', answers["name"]),
        AddToTsConfigPaths(plop, 'tools', answers["name"])
      ];
    },
  });
}
```
