### ISSUE TITLE
'force' parameter not working in `'add' and `addMany' actions

### ISSUE THREAD

**Issue by SilasReinagel** [amwmedia/plop#164]
Plop v2.3.0 - Win10

Using this action in my plop generator:
```
    {
      type: 'add',
      path: '{{projectLocation}}',
      templateFile: './templates/microservice-dotnet-servicefabric/MyCompany.{{name}}.sln',
      force: true
    }
```

Results in this error:
```×  ++ Cannot delete files/folders outside the current working directory. Can be overridden with the `force` option.```

**Comment by amwmedia** [comment]
A few things:
1. Is `{{projectLocation}}` available within the handlebars data or is it a local variable? If it's a local variable, handlebars won't know about it.
2. You're using a handlebars template value in your templateFile path, make sure that it is correctly resolving to a file that exists.
3. All paths are (by default) relative to the plopfile path. So, if your plopfile is in your project root, you may not need to specify "projectLocation".

**Comment by SilasReinagel** [comment]
### 1. Project Location is supplied as a prompt. It's available and working in other actions.

### 2. The filename is named `./templates/microservice-dotnet-servicefabric/MyCompany.{{name}}.sln`
Maybe this is the problem? This format works with the `addMany` action, since it matches a glob pattern and when the file is moved, it is also named. Perhaps it doesn't work the same way in `add`

### 3. Path is presently being used to specify the destination location.

**Comment by amwmedia** [comment]
Ah, I see. So, it looks like this is probably an issue with your `path` pointing to a directory instead of a file path. The `add` action expects `path` to be the exact path (including filename) that the file should be generated as.

So if you change `path` to include "/Carvana.{{name}}.sln" at the end, it should work.

**Comment by SilasReinagel** [comment]
That still doesn't seem to work. 

![image](https://user-images.githubusercontent.com/10834339/60040970-0a4f0d80-966f-11e9-8b90-7dc0f43a1d93.png)

**Comment by amwmedia** [comment]
looks to me like this is a constraint with the `del` package not wanting to remove things (overwrite) outside of the `cwd`. We likely need to pass the plop `force` value into `del` in order to make this work.
