### ISSUE TITLE
`plop -i` twice crashes

### ISSUE THREAD

**Issue by kud** [amwmedia/plop#167]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/655838/60586755-0881fa00-9d93-11e9-9ca6-dd70d8328db3.png">

**Comment by amwmedia** [comment]
thank you for reporting thing 👍

**Comment by kud** [comment]
You're welcome!

And thanks for your project, I just tried it, it's amazing!

**Comment by Jmoore1127** [comment]
Getting this as well

**Comment by kud** [comment]
Thanks!
