### ISSUE TITLE
Adding actions conditionally depending on previous answers

### ISSUE THREAD

**Issue by manuelbieh** [amwmedia/plop#18]
I haven't found it in the example file or in the readme so I'm not sure if that is already possible. If not, I would like to file a feature request here ;)

I am using plop to create a json configuration which can contain a `selector` property with an array as value which is freely expandable and can hold 1-n items. In my case it's a css selector. I have now created an action to add a new css selector:

```
{
    type: 'prompt',
    name: 'selector',
    message: 'Enter a css selector to add:',
}
```

What I am now looking for is to jump back to `prompts[0]` in case `prompts[1]` is answered with yes:

```
{
    type: 'confirm',
    name: 'addMore',
    message: 'Add another css selector?',
}
```

So what I would like to have is something like this:
```
[PLOP] Please choose a generator. cssconfig
[TEST] Enter a css selector to add: .foo
[TEST] Add another css selector? Yes
[TEST] Enter a css selector to add: .bar
[TEST] Add another css selector? Yes
[TEST] Enter a css selector to add: .foobar
[TEST] Add another css selector? No
[SUCCESS] add W:\test.js
```

The generated file should then contain something like:

```
{
  "selector": [".foo", ".bar", ".foobar"]
  [...]
}
```

Sure, in my example I could just allow to write several selectors comma separated but I can think of other usecases where you might want to have further actions based on previous selections. 

So is it possible? If not, can it be (more or less) easily added as feature? (Probably it's more a inquirer issue than plop, isn't it?)

**Comment by amwmedia** [comment]
Yeah, I believe this would be solved via an inquirer plugin. At least the way you are envisioning it. You could alternatively have the user type out a comma delimited list of classes they want added and process that data via a custom action function.

**Comment by amwmedia** [comment]
sounds like what you really want is an inquirer plugin that would accept multiple prompt definitions and loop over them until the user was finished. Something like this could create an array of answer objects that would live in the main answer object. If you want to write such a plugin, I'd be happy to feature it in the [custom inquirer prompts](https://github.com/amwmedia/plop/blob/master/inquirer-prompts.md) page :wink:
