### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by datwheat** [amwmedia/plop#19]
I was wondering: what terminal emulator is running in your screenshot gif in the readme?

Thanks

**Comment by amwmedia** [comment]
I use [fish shell](http://fishshell.com/) with [iterm2](https://www.iterm2.com). The color scheme is seti from the [iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes) repo, and I use the [hack](http://sourcefoundry.org/hack/) font (which includes the powerline glyphs).
