### ISSUE TITLE
Generate multiple files using * (glob)

### ISSUE THREAD

**Issue by raabbajam** [amwmedia/plop#21]
This is a feature request, to generate multiple files in one action. Something like generate `src/modules/{{lowerCase name}}/*.js` from templates in `plop-templates/modules/*.js` using the asterisk / glob (*).

e.g `plop-templates` folder

```
plop-templates/modules/index.js
plop-templates/modules/parser.js
plop-templates/modules/utils.js
plop-templates/modules/helpers.js
plop-templates/modules/others.js
plop-templates/modules/anothers.js
```

And then in `plopfile.js`:

```
...
prompts: [
      {
        type: 'input',
        name: 'name',
        message: 'What is the module name?',
      },
    ],
    actions: [
      {
        type: 'add',
        path: 'src/modules/{{lowerCase name}}/*.js', // <--- here are the globs
        templateFile: 'plop-templates/modules/*.js', // <--- globs
      }
]
...
```

and command `plop module foo` will generate:

```
src/modules/foo/index.js
src/modules/foo/parser.js
src/modules/foo/utils.js
src/modules/foo/helpers.js
src/modules/foo/others.js
src/modules/foo/anothers.js
```

Your great works are much appreciated. Cheers :coffee:

**Comment by amwmedia** [comment]
interesting idea, how would you see this working with a glob like `src/modules/{{lowerCase name}}/**/*`? I think you would have trouble reconciling the 2 globs and figuring out what to do. With a glob you almost need a destination folder to just dump everything into.

**Comment by amwmedia** [comment]
this might work with a different action name. Something like `addMany` that could take a `templateFiles` glob and use a `destination` property instead of `path`. Then you could just process all of templates and dump them into the destination folder.

**Comment by nicoespeon** [comment]
Agreed that using a glob should redirect to a directory.

So, if I sum it up, this is basically what we'd like to achieve right?

```javascript
plop.setGenerator('custom-prompt', {
  // …
  prompts: [
    {
      type: 'input',
      name: 'name',
      message: 'What is the module name?',
    }
  ],
  actions: [
    {
      type: 'addMany',
      destination: 'src/modules/{{lowerCase name}}/',
      templateFiles: 'plop-templates/modules/**/*.js'
    }
  ]
});
```

**Comment by nicoespeon** [comment]
I am wondering: if we have a specific `addMany` action to plop a glob into a folder, should we have

```javascript
{
  type: 'addMany',
  destination: 'src/modules/{{lowerCase name}}/',
  templateFiles: 'plop-templates/modules/**/*.js'
}
```

Or could we consider that sources could only be a folder:

```javascript
{
  type: 'addMany',
  destination: 'src/modules/{{lowerCase name}}/',
  templateFiles: 'plop-templates/modules/'
}
```

The latter is simpler. It is less flexible though.

What do you think?

**Comment by nathanloisel** [comment]
Hey guys,

It's a really interesting feature !
In my opinion, it can be very usefull to use pattern **/*.xx, it can allow to use different language like .ts or .js regarding to a hypothetical basic configuration. However, use both pattern (with a regex and with the source dir only) seem to be easy to implement.

This feature should be implemented in node-plop project i think. Tell me if any help is needed to implement it.

**Comment by nicoespeon** [comment]
@nathanloisel yep the glob would be more flexible. Though, you could still create different template folders to group files that are related. I'd understand both, it really depends on what we'd like plop to be like − @amwmedia, what do you prefer?

And yep, it's completely part of node-plop.

I'm playing around with that, see what I can do. Once I am clear on the desired API, I'd submit a PR for this so we could discuss the implementation 👍

**Comment by amwmedia** [comment]
I'd love to use globs, and even accept an array of globs like many projects have done. I think it may be necessary to also include a `base` property (similar to what [gulp does](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase)) to allow the action to know how the template file paths relate to the destination.

Basically we need to have a way to answer the question of whether the path created by this action...
```javascript
{
  type: 'addMany',
  destination: 'src/modules/{{lowerCase name}}/',
  templateFiles: 'plop-templates/modules/**/*.js'
}
```
...should include the `modules` directory, `plop-templates` directory, etc? So it's basically the part of the fully qualified path that gets subtracted when constructing the new path.

Also, I suppose if you wanted the individual files to have custom names in the outputted code you could use handlebar notation in your file names. This feel a little weird, but maybe that's ok?

**Comment by amwmedia** [comment]
Also, take a look at the [custom actions](https://github.com/amwmedia/node-plop/tree/custom-actions) branch of node-plop. It has the new structure where actions are now separate modules.

**Comment by nicoespeon** [comment]
Thanks for indications 👍 

I started giving it a try, then I got my computer stolen last week. I've been idle a bit since as I needed to restore a fully functional work environment, among other troubles this caused to me…

I'll get back to it when I got some free time 😉

**Comment by amwmedia** [comment]
@nicoespeon sorry to hear that! Hope you are able to get back to normalcy soon 😄

**Comment by nicoespeon** [comment]
Hey @amwmedia!

FYI, I started to implement a `addMany` action in node-plop, based on the `custom-actions` branch.

I need to add more tests to handle different scenarios. But I'll probably open a PR anytime soon so we can discuss on concrete code and craft the API together, see how we answer the questions you pointed out (e.g: which parts of the `templateFiles` should be dropped, can individual file names have custom names, can we merge this action into the `add` one without making things weird…).

**Comment by amwmedia** [comment]
[addMany](https://plopjs.com/documentation/#addmany) has been added in plop v1.8.0

**Comment by RayKay91** [comment]
append many would be really useful too 🙏
