### ISSUE TITLE
Run plop from Node

### ISSUE THREAD

**Issue by andrewjensen** [amwmedia/plop#22]
I'm on a team that uses a somewhat complex plopfile and I'd like to have a quick way to verify that it is working the way we want. I would love to be able to `require('plop')` and automatically generate some components with defaults.

The interface for my script might look something like this:

```javascript
var plop = require('plop');
var path = require('path');

var exampleDir = path.resolve(__dirname, 'example');

plop.runGenerator('widget', {
  // Use the same variables as the prompts require
  path: path.resolve(exampleDir, 'widgets'),
  name: 'my-widget',
  animal: 'dog'
});

plop.runGenerator('complexWidget', {
  path: path.resolve(exampleDir, 'complex', 'widgets'),
  name: 'my-complex-widget',
  animal: 'hippo'
});
```

@kentcdodds this might be a good way to verify your plopfile settings, as an alternative to #7.

**Comment by amwmedia** [comment]
I'll look into this, if it could be coded to return the output you could then run asserts against the generated output. That could be really sweet. good idea! :+1:

**Comment by amwmedia** [comment]
come to think of it, this could work for `add` actions, but in order to do this for an entire generator we would need to implement a virtual file system. this is possible, but would not be a trivial change. :frowning: Maybe something like this could be done at the individual action level? Not sure, but I'm open to ideas.

**Comment by andrewjensen** [comment]
To be honest, I'm actually more interested in just using the normal filesystem but through a Node API rather than a command line interface. It looks like if we could decouple the template generating logic from the inquirer prompts, it would come relatively easily.

**Comment by amwmedia** [comment]
true, I think that much is doable, but it wouldn't function all that well for unit testing if it's actually mucking with your source code. Do you have something in mind for how you're planning to handle this? I'm more curious than anything :smile:

**Comment by andrewjensen** [comment]
I think you're right - adding a Node API probably wouldn't be useful for unit testing. For my current needs, I basically need a way to call plop in a script for quick-and-dirty verification that the generators look right.

A little background about my use case: my team works on small Angular apps and uses a common plopfile packaged into a node module so we can maintain a consistent structure on each app. We're in the middle of changing a lot about our tooling and app architecture, so the plopfile is changing a lot at the moment. My plan is to write a script that calls a bunch of generators inside of a `sandbox/` directory that is ignored by git, so when I review a pull request for an improvement to the plopfile, I can quickly explore the generated output without the template variables getting in the way.

**Comment by amwmedia** [comment]
I've been giving this some thought, and my plan is to break the core of plop out into a new npm package that plop would require. That would enable much of what I think you're trying to achieve, and also make it possible to work with plopfiles and generators in other ways. Just FYI, I'm currently working on a website for plop so this will have to wait for a bit. Hopefully I'll be able to get to it in the coming month.

**Comment by amwmedia** [comment]
just pushed up the first pre-release version of node-plop, please have a look and let me know if you run into any issues 😄

https://github.com/amwmedia/node-plop
it's also up on npm 
https://www.npmjs.com/package/node-plop

**Comment by rdewolff** [comment]
That's a good news that we can use `node-plop`
