### ISSUE TITLE
Call generator within another generator

### ISSUE THREAD

**Issue by kevin-wolf** [amwmedia/plop#24]
Let's say I have the following generators:

- module
- model
- view
- controller

I want the `module` generator to internally call `model`, `view` and `controller` generators.

Is there an API method to achieve this?

Cheers.

**Comment by amwmedia** [comment]
currently there is no way to run a generator outside of running the CLI. Are you looking to trigger the entire `prompts => actions` process, or just the actions?

**Comment by kevin-wolf** [comment]
Just the actions. I know that I can declare the function and call them, like this:

```javascript
plop.setGenerator('model', {
  description: 'app model',
  prompts: [...],
  actions: [ generateModel ]
});

plop.setGenerator('module', {
  description: 'app module',
  prompts: [...],
  actions: [ generateModule, generateModel, generateController ]
});
```

But i find that approach a little verbose, what if I have separate generator files? (Ex `module.js`, `model.js`), I will have to export the functions, etc.

It will be fine an API method like this:

```javascript
plop.callGenerator('generatorName', { });
```

**Comment by amwmedia** [comment]
you could use the `plop.getGenerator(name)` api method to get the generator config object, then concat the `actions` array from there. But yeah, I see what you mean. I'm going to be working on exposing something like this for issue #22. So once that gets resolved it would probably work for this.

**Comment by kevin-wolf** [comment]
Excellent! You can close the issue then.

**Comment by amwmedia** [comment]
just pushed up the first pre-release version of node-plop, please have a look and let me know if you run into any issues 😄

https://github.com/amwmedia/node-plop
it's also up on npm 
https://www.npmjs.com/package/node-plop
