### ISSUE TITLE
Support for one time configuration

### ISSUE THREAD

**Issue by NetanelBasal** [amwmedia/plop#25]
If I want to give the user, for example, to choose which css preprocessor he preferred sass/less/stylus ( for the file extension ) and I need to save this somewhere for not asking him again every time, There is a way to do that?

**Comment by amwmedia** [comment]
I'm working on a way to let plop do a one time setup of an entire codebase. So this would allow a user to clone your repo, run plop and answer some questions, then plop would make the appropriate changes to the codebase to customize it. This is not in place yet, but it is definitely on the roadmap along with sharable plop "packs" that would allow you to publish a set of generators that others could use in their own plopfiles.

Would this feature (once available) fit your need?

**Comment by NetanelBasal** [comment]
Yes, thank you.
