### ISSUE TITLE
Skip prompt if name argument supplied

### ISSUE THREAD

**Issue by marsh73** [amwmedia/plop#28]
ie ( 'plop component myComp' ), given that I have a generator named 'component', I would like to skip the prompt for name if the their is a name argument passed in. I am able to access the argument via this.process.argv[3], but it seems I can't use 'prompts' property as a function, so I am unable to add any conditional logic here as I can with actions. Is there an easier way to do this?

**Comment by amwmedia** [comment]
hmm, there might be a case for making prompts able to handle being a function as well (like actions). But let me give this a little more thought, there might be a better way to fully support this type of workflow. I've often thought that it would be nice to just write `plop component someName` but it really only makes sense if you have a lot of generators with only 1 prompt.

**Comment by gagoar** [comment]
+1 
We are using plop for our design system where we relay heavily on the generator to create components and icons, etc. Sometimes to speed things up we would like to supply `options` (plop component --`inputName` `inputValue` ) and avoid that prompt completely. Could we propose to add this? It should be fairly transparent and generic giving that prompts `input` have a `name` key. we can leverage.

**Comment by albybarber** [comment]
👍  +1

**Comment by amwmedia** [comment]
so, if we made it so that you could execute `plop component --name "user list" --size medium` would that suite the need? the only issue I have with that is that there's no way to know what `--attribute` you would need to use without looking at the plopfile.js code. But maybe that's ok. Or maybe we need to alter how each prompt is being given so that the attribute name is surfaced... meaning... if I just do `plop component`, should the prompt for `name` have the word "name" somewhere (ie: "[name] What should we call this component?")? 

Thoughts? @albybarber @gagoar @marsh73

**Comment by gagoar** [comment]
yea, we could show a generic answer to display the properties offered. like generic `--help` perhaps ?  

also this would provide for a really nice API so we could integrate plop to any runner (like gulp or grunt) if needed.

**Comment by albybarber** [comment]
Yeah that would work! I am not really to worried about the surfacing of named attributes because if you are using this `power user` feature you would already know the names.

Thanks.

**Comment by amwmedia** [comment]
ok, thanks for the feedback! @gagoar might be able to implement something like `plop component --prompts` that would list out the prompt data. Or maybe (like @albybarber mentioned) we just leave it as a feature that you really only can use if you understand how the prompts are structured. 

Though, if we take that approach, I'm inclined to just let that fall to node-plop. I'm like 90% done with it and it would allow you to run a generator programmatically from any node script. Would that suite everyone's needs better?

**Comment by gagoar** [comment]
that could work just fine. where we can see node-plop ? I think that would be exactly what we need actually

**Comment by amwmedia** [comment]
nothing to see yet, I have it developed locally ;-)

**Comment by amwmedia** [comment]
I'll let everyone know here when it's released, the repo is over at https://github.com/amwmedia/node-plop if you want to watch it.

**Comment by gagoar** [comment]
@amwmedia thanks ! ping us if you need help. We would be happy to contribute !

**Comment by amwmedia** [comment]
just pushed up the first pre-release version of node-plop, please have a look and let me know if you run into any issues 😄 

https://github.com/amwmedia/node-plop

**Comment by amwmedia** [comment]
closing this for now because I believe node-plop is going to be the solution for this
