### ISSUE TITLE
foreach and other advanced tempting features

### ISSUE THREAD

**Issue by fleed** [amwmedia/plop#31]
Is it possible to use statements (foreach, if, etc.) in templates?
If not:
- is it planned for future releases?
- any workaround?

**Comment by amwmedia** [comment]
yes! plop uses the handlebars template engine and [has all of these features](http://handlebarsjs.com/builtin_helpers.html), plus the ability to add custom features if you so desire. You can learn more on [their website](http://handlebarsjs.com).
