### ISSUE TITLE
Replace existing files

### ISSUE THREAD

**Issue by fleed** [amwmedia/plop#32]
Is it possible to force the replacement of existing files?
That's required when running the generator after changes (example: template updated)

**Comment by amwmedia** [comment]
well, if you run this after a template update, you would replace the files in their entirety. Which means you would loose any updates you made (the unique stuff) that was in them. I think the risk of overwriting an existing module that you didn't realize was already there, is pretty important here. I have (several times actually) tried to plop a helper that another team member had already plopped before and I was very happy that plop didn't let me overwrite the existing module.

Maybe the ideal setup would be that plop looks ahead and sees if the files that it is about to create already exist. If they do, the user could be prompted to decide if they want to overwrite the files, or abort.

**Comment by fleed** [comment]
I think that by default it should prompt the user for choices like the "ng init" command (overwrite, skip, show difference), but there should also be a "force" flag if the user wants to replace all files.

**Comment by amwmedia** [comment]
agreed that plop should prompt the user, I'm re-opening as a reminder to add this feature

**Comment by rdewolff** [comment]
an option would be great :)

**Comment by iwinux** [comment]
As a reference, Yeoman shows the diff of old / new files when conflict is detected.

**Comment by kentcdodds** [comment]
My use case is also for a generator. If someone wants to migrate from a custom project to my generator then they would need to be able to choose between overwrite all, overwrite none, or per-file overwrites.
