### ISSUE TITLE
Modify action for json files

### ISSUE THREAD

**Issue by adrianmroz** [amwmedia/plop#33]
My proposition is to add a modify action for JSON files, where you will provide callback instead of pattern and template. In callback you would get `JSON.parse`d object and you should also return POJsO which will be `JSON.stringify`d and written to file.

**Comment by wbobeirne** [comment]
I went ahead and made a custom action for this, but I definitely think this could get rolled in as a flag on `modify` action types or something. Here's the code for alterJsonAction.js: https://gist.github.com/wbobeirne/63e1b8c3a16ffce6dac5c7d81afd5cec?ts=2

Example usage from my use case is:
```
actions: [alterJsonAction({
	path: "../webpack/entries.json",
	alter: (json, data) => {
		const name = snakeCase(data.name);
		json[data.platform][name] = `pages/${name}`;
		return json;
	},
})],
```
I also threw in an `indentation` arg there that takes an int or "\t", if 2 spaces ain't your game.

**Comment by amwmedia** [comment]
sorry for the late response, I agree that this would be pretty useful in some cases. I'll have to give some more thought to the best implementation for this feature. Thanks!

**Comment by amwmedia** [comment]
hey, with plop 1.8.0 you can now create [custom action types](https://plopjs.com/documentation/#setactiontype) that you can share with other projects :-)

**Comment by mritzco** [comment]
I created a custom action type to add data to my config.json file.
Tried to follow the plop style to keep it customizable.

https://gist.github.com/mritzco/88306b56c0184e66e33374d6b6ed2751

**Comment by amwmedia** [comment]
nice! You could publish this out as an NPM module that others can use via [plop.load()](https://github.com/amwmedia/plop/blob/master/plop-load.md). If you want to do that and need help, let me know.

**Comment by mritzco** [comment]
I'll happily do! Just publish to npm or any specific requirements?

**Comment by amwmedia** [comment]
Sorry for the delay on this response. You can look at [this repo](https://github.com/amwmedia/plop-pack-fancy-comments) as a guide to how this is done. I'm going to try to get more instructional content together soon.

**Comment by mritzco** [comment]
@amwmedia 
Ok, that took a bit longer than expected:   

Could you please take a look at this [repo](https://github.com/mritzco/plop-pack-json-modify ) and let me know if that would do.

Original method gets the config on the method call, while the load method passes the config on the require function. It's working with the testing file but I'm not sure it will work properly in all cases.
