### ISSUE TITLE
plop fails if `prompt` property is omitted in plopfile.js

### ISSUE THREAD

**Issue by despairblue** [amwmedia/plop#34]
Example: https://gist.github.com/despairblue/82a7bd6a16eccdbb7856493fb4d79c0a

Running `node_modules/.bin/plop` doesn't create a file or return an error code. When adding `prompts` everything works again.

**Comment by amwmedia** [comment]
Thanks, I'll look into adding some validation for the generator structure before executing it.

**Comment by amwmedia** [comment]
this issue will be taken care of in the next plop release when I integrate `node-plop`. `node-plop` addresses this issue in release [v0.3.0](https://github.com/amwmedia/node-plop/releases/tag/v0.3.0). stay tuned...

**Comment by amwmedia** [comment]
this should be fixed now in v1.6.0
