### ISSUE TITLE
Windows 10 can't navigate

### ISSUE THREAD

**Issue by mnemanja** [amwmedia/plop#35]
Hi, I'm having a trouble to use arrow keys to navigate. I've tried **cmd** and **git bash**, as well as the **webstorm terminal**.

I'm testing it as a part of the react-boilerplate. This is the pre-anniversary win10.

**Comment by amwmedia** [comment]
yeah, the prompt data is sent directly to inquirer to handle the user input. Not sure that there is much that can be done in plop if this is a problem between Windows and inquirer. 😦 

I see that mxstbr/react-boilerplate#847 has been closed, was this resolved?

**Comment by amwmedia** [comment]
Thanks! so it looks like you can fix this issue by updating your node to one of the working versions 👍

**Comment by mnemanja** [comment]
I can confirm that it works with Node 6.2. 
Thanks @Dattaya.
