### ISSUE TITLE
Document liftoff arguments

### ISSUE THREAD

**Issue by wbobeirne** [amwmedia/plop#37]
I was looking for a way to supply my own paths and things of that nature, but --help and the readme were not helping. But they're in there, just undocumented https://github.com/amwmedia/plop/blob/master/plop.js#L24

**Comment by amwmedia** [comment]
hey, thanks for bringing this to my attention. I'll get the documentation in for this. The liftoff support was added by a contributor, and I must have missed the fact that these command line args were added.

**Comment by nicoespeon** [comment]
Hey @amwmedia!

I think this one is closed with merge of #59, isn't it?

**Comment by amwmedia** [comment]
Yes, it is. @wbobeirne this will be in the next release.
