### ISSUE TITLE
Customize the starting prompt

### ISSUE THREAD

**Issue by codTango** [amwmedia/plop#39]
The starting prompt says: "[PLOP] Please choose a generator. (Use arrow keys)" each time when I run plop, is it possible to customize it to some other message?

**Comment by amwmedia** [comment]
I'm probably going to make some changes to how "[PLOP]" shows up throughout the process. I'll need to look at whether it's possible to also add a way to customize this initial message as well. Right now I don't think it's possible (as things are today)

**Comment by nicoespeon** [comment]
Hey!

Is that something we still want to do?

If so, I was thinking of a `plop.setStartingPrompt(message)` that could be called in plopfile to change the message. But I'd like your feeling on it: does it worth it?

If it does, I've got a quite clear idea about required changes, so it can be done pretty soon (as things are today 😉).

**Comment by amwmedia** [comment]
yeah, that'd be great 👍. I've been meaning to get to some of these types of low-hanging-fruit tickets for a while but always seem to get consumed by things that are large... or look small but end up being large haha
