### ISSUE TITLE
Is plop using node-plop?

### ISSUE THREAD

**Issue by calcaide** [amwmedia/plop#43]
@amwmedia As you said in issue #20 (if I understood well) plop is using node-plop internally, right?
Supossing that, I can see that plop is not requesting node-plop, in fact, the files are duplicated, please correct me if I am worng. That confuses me a bit, actually, that's why I didn't realise that plop is using node-plop.

In case that my assumption is correct, what do you think about using node-plop as a module?

**Comment by amwmedia** [comment]
ah, sorry for the misunderstanding. What I meant to say was that plop needs to be changed so that it uses node-plop internally. That is a change that still needs to happen.

**Comment by calcaide** [comment]
No worries 😉 , I did the question just to figure out in what project I have to focus first, now is clear, I will put my effort in node-plop.

**Comment by amwmedia** [comment]
sounds good, I'm in the middle of a revamp of the code. simplifying with `co`, es6 Promises, etc. Should be a lot easier to read the code and follow when I'm done.
