### ISSUE TITLE
Totes amaze!

### ISSUE THREAD

**Issue by penrillian-chrisa** [amwmedia/plop#47]
Just a quick line to say thank you for creating plop. Why haven't I heard about it before?

I'm using it to create assets for a [HAPI](http://hapijs.com/) server, and although it took a couple of hours to get it in place, it's going to save so much time.

**Comment by amwmedia** [comment]
Thanks for kicking off my week with that warm fuzzy feeling ;-). I'm really glad you are loving plop!
