### ISSUE TITLE
Windows 8.1 doesn't work. Says "can't find a module ..."

### ISSUE THREAD

**Issue by Krekotun** [amwmedia/plop#53]
I tried to run it from local `node_modules/.bin`
Then I installed it as global dependency, generated a new plopfile `plop -i` and run it. Nothing 

Here is the screenshot http://d.pr/i/13ELg2

On macOS I have no problems.

**Comment by amwmedia** [comment]
Thanks for raising this, I will be looking into it Monday morning and should have a patch out shortly

**Comment by amwmedia** [comment]
resolved in v1.7.1, please let me know if you see any other issues

**Comment by Krekotun** [comment]
Thanks, I'll check asap
