### ISSUE TITLE
Enhance error message returns

### ISSUE THREAD

**Issue by tpizza** [amwmedia/plop#54]
Something that came up when I was plopping files:

It being so late, haha, I was trying to reference the pascalCase helper within handlebars with a literal PascalCase.

Instead of throwing the error ` Missing helper "PascalCase" ` from the message prop within the error object instead the only error output printed in the console was ` [FAILED] undefined undefined undefined `

Maybe we include the error message in the fail by default and use a falsy to check for a line.type to determine if we should output the additional props?

**Comment by amwmedia** [comment]
oh, haha, yeah, I'll see if we can pull an error out of handlebars when it compiles the template and bubble that up. Thanks!
