### ISSUE TITLE
Is there a way to read the users input in validate

### ISSUE THREAD

**Issue by kopax** [amwmedia/plop#55]
I have a select that purpose a folder list.

In the next step, I need to validated to ask him to type a folder name.

I will have to read the value of the folder list choice in order to write the validate function.

Is that possible ? to read the user input ? I've looked everywhere in the documentation it's like missing.

**Comment by amwmedia** [comment]
so, to clarify, you need to alter something about prompt 2 based on the answer given in prompt 1?

**Comment by amwmedia** [comment]
Plop uses inquirer syntax, so from the sound of it, you might be able to handle this case with the `when` property of the [Question Object](https://github.com/SBoudrias/Inquirer.js#question) spec.

**Comment by kopax** [comment]
@amwmedia yes it's exactly that.

I have read the `when` definition, could you provide a sample case I don't really understand what 

` and should return true or false depending on whether or not this question should be asked.`

mean in this situation

**Comment by amwmedia** [comment]
I don't believe you can use the answer to a previous question to alter the values of a question asked later. I think your only option is to have questions in the array for the various scenarios that are possible and use `when` to decide which question should be asked. This doesn't play nice with "decision tree" type scenarios, but there may be other options I'm not aware of. I'd suggest posting this issue over on the inquirer repo as it is specific to their syntax and someone over there is likely more qualified than myself to help you solve this :-)

That said, the follow is the only solution I can personally think of.

```javascript
{
	prompts: [{
		type: 'checkbox',
		name: 'social',
		message: 'What social media networks do you use?',
		choices: [
			{name: 'Twitter', value: 'tw'},
			{name: 'Facebook', value: 'fb'}
		]
	}, {
		type: 'input',
		name: 'twitterHandle',
		message: 'What is your twitter handle?',
		when: (answers) => answers.social.includes('tw')
	}, {
		type: 'input',
		name: 'facebookHandle',
		message: 'What is your facebook handle?',
		when: (answers) => answers.social.includes('fb')
	}]
}
```

**Comment by kopax** [comment]
I solved it like this 

```
        let tmp;

	prompts: [{...myTasks}, {
		when: (answers) => { tmp = answers}
	}, {...myTasksPart2}]
```

**Comment by amwmedia** [comment]
deliciously hacky... I like it ;-)
