### ISSUE TITLE
Let `pkg` helper resolve property paths out of the box

### ISSUE THREAD

**Issue by jrencz** [amwmedia/plop#57]
It may be useful to reach deeper than the 1st level of the package object.

I suggest plop should come bundled with `pkg` anyone can override like this:

```js
const get = require('lodash.get');
const pkg = require('./package.json');

plop.addHelper('pkg', propertyPath => get(pkg, propertyPath));
```

It may be taken right from lodash like I suggested above or it can be replicated in this project if you don't want more dependencies.

**Comment by amwmedia** [comment]
Thanks for the suggestion, I like how this extends the functionality without breaking the core functionality that already exists 👍

**Comment by jrencz** [comment]
@amwmedia do you want me to prepare PR for exactly how I described it?

**Comment by amwmedia** [comment]
if you'd like to, sure :-). This would need to be made over on [node-plop](https://github.com/amwmedia/node-plop/blob/master/src/modules/node-plop.js#L17)

**Comment by jrencz** [comment]
amwmedia/node-plop#30
