### ISSUE TITLE
Add `addPartial` method

### ISSUE THREAD

**Issue by kentcdodds** [amwmedia/plop#6]
I have a use case for this capability. I've tried requiring handlebars myself and adding the partial that way but that doesn't appear to register it with the instance being used by plop somehow because I get an error that my partial could not be found.

**Comment by amwmedia** [comment]
Yeah, makes sense, this should be pretty easy to do. I'll try to get the pass through function in there soon.

**Comment by kentcdodds** [comment]
Thanks :clap:
