### ISSUE TITLE
Autorunning generators

### ISSUE THREAD

**Issue by NoNameProvided** [amwmedia/plop#60]
I am using plop kind of a time now, it saves a lot of times, so thanks for it! 

Now I have tried to autoload generators, when scaffolding a project, but I couldnt figure out how to do it. Is it possible, did I missed something? I want to run it on my `postinstall`, so a command like `plop page --name=index` would make sense.

**Comment by amwmedia** [comment]
Hey, there's currently no way to do this with the CLI (though I have been thinking of ways to make it happen). However, you can easily do this with [node-plop](https://github.com/amwmedia/node-plop) which is the package that runs all of plop's core capabilities under the hood.

**Comment by NoNameProvided** [comment]
Thanks, will take a look. Anyway it would make sense to have this, its nicer to run only plop in a postinstall hook than write a script for it and ship one more dependency.

**Comment by amwmedia** [comment]
I don't disagree, it's just a matter of finding a way to do it that doesn't potentially conflict with existing application flags. I've recently thought about using the `--` as a way to do this. If something is added I'll certainly let you know.

Can you explain your use case for me? Seems like if you want this to run on postinstall, you could just as easily have the codebase just include the index route to start with. I'm sure I'm just missing something here.

**Comment by NoNameProvided** [comment]
I am using it in a starter, and the reason behind this is that I want to allow projects to update the starter after they started using it in their project (`git pull upstream master`). To achieve this I cannot commit files which will be edited by the users, so I need to generate the starter files of the src folder after npm install. 

>  I've recently thought about using the -- as a way to do this. 

Hmmm, npm uses this to pass parameters to scripts (`npm run generate -- page` will run `plop page`). I don't know how well `npm` can play with others when using this pattern.

**Comment by amwmedia** [comment]
thanks for the clarification! 

As for npm and `--`, good to know. It's just something I'd need to test. I don't think it would be a problem.
