### ISSUE TITLE
Built-in pluralize helper support

### ISSUE THREAD

**Issue by yangshun** [amwmedia/plop#63]
I just discovered Plop and was amazed by how easy it is to use! Kudos to you sir!

I would like to ask if there are plans to add support for a built-in `pluralize` helper so that I can emulate what Rails does when I run the `rails generate scaffold` command, to generate certain file/folder names contain the plural version of the input I pass into my plop generator.

If you are open to that idea I can make a PR for it 😄

**Comment by amwmedia** [comment]
Yeah, you could pretty easily use something like the [handlebars-helper-pluralize](https://www.npmjs.com/package/handlebars-helper-pluralize) to accomplish this. As far as providing a built-in helper, I would not think that this would be used enough to warrant going in at that level.

I've been trying to keep the built-in helpers to including only those helpers which would be used in 90% of projects.

**Comment by yangshun** [comment]
Thanks, I ended up doing that 😄 

Got it, will close this since it's not relevant.
