### ISSUE TITLE
Document validate of setGenerator Prompts

### ISSUE THREAD

**Issue by MartinMuzatko** [amwmedia/plop#64]
Hello!

Partially, there is no documentation for the fields a prompt or action can have.
I only found that information by reading the example plop file.

Please document the `validate` property of prompts.

**Comment by MartinMuzatko** [comment]
I found the documentation: https://github.com/SBoudrias/Inquirer.js/#question
I forgot it when I was already down in the documentation.
Feel free to close this issue.

**Comment by amwmedia** [comment]
Glad you were able to find this so quickly. I'll consider adding a section that explains question objects and where to find documentation for them. 👍
