### ISSUE TITLE
Do not ask which generator to use, when there is only one

### ISSUE THREAD

**Issue by MartinMuzatko** [amwmedia/plop#67]
Do you think it makes sense to just use the generator and start asking questions instead of picking one, if there is only one to pick?

**Comment by amwmedia** [comment]
I'm not sure, I'd be interested in hearing what others think about this. I could sort of go either way on it. On one hand, it's convenient for it to take one step out of the mix. On the other hand, having the extra step in there makes for a consistent experience.

**Comment by duclet** [comment]
I like the idea of automatically choosing if there is only one option. While it may be inconsistent, what is the point if asking for user input if they are simply given one option?

**Comment by TheSisb** [comment]
I would really like this.  At the very least there could be a way to skip into it.
