### ISSUE TITLE
file generated relative to current directory

### ISSUE THREAD

**Issue by robhicks** [amwmedia/plop#68]
I'm new to plop.

I followed the advice of putting the plopfile.js file at the root of my project. 

When I ran plop the first time, I ran it from a subdirectory of the project. I expected it to create the files relative to the current subdirectory. It didn't. It created them at the root of the project. 

Is there an easy way to get plop to generate the files in the current subdirectory without asking for it? I finally used ```plop.addHelper('cwd', (p) => process.cwd());``` and then prefixed all of my path strings with ```{{cwd}}/```.

**Comment by amwmedia** [comment]
Hi @robhicks, I believe you landed on the correct solution for what you want to accomplish here.

The reason plop uses paths that are relative to the plopfile by default is to help enforce consistency in the directory structure. I've found that this works well for most codebases, and if the `cwd` is desired, a simple helper can provide that functionality (as you found).

**Comment by chiptus** [comment]
can this be documented somewhere? I think it might be a common need
