### ISSUE TITLE
Testing example?

### ISSUE THREAD

**Issue by kentcdodds** [amwmedia/plop#7]
While building these things, I'm finding that it would be really nice to be able to run some tests rather than having to test in manually. Do you think we could develop a good way to do that? Even if it's just some examples that would be handy. But being able to assert files were created and their contents without actually creating them would be really helpful.

**Comment by amwmedia** [comment]
Agreed! This would be really nice. I would need to give some thought to how something like this could be implemented.

**Comment by amwmedia** [comment]
Not sure there can be a full solution for this. With the functionality of modify, and custom actions, I can think of no way to validate what a generator does in a sandboxed test environment. You would need some sort of virtual file system that can be constructed and throw away. Let me know if you have any ideas.

**Comment by kentcdodds** [comment]
How about [memfs](https://www.npmjs.com/package/memfs)? :-)

**Comment by amwmedia** [comment]
of course! why wouldn't there be a node module that does exactly what we need! ;-) I need to do a little reading. I haven't used an in-memory virtual file system before. any chance you happen to be an expert in this area?

**Comment by amwmedia** [comment]
oooo, [mock-fs](https://github.com/tschaub/mock-fs) might do the trick

**Comment by kentcdodds** [comment]
Never done it before myself.

**Comment by amwmedia** [comment]
just pushed up the first pre-release version of node-plop, please have a look and let me know if you run into any issues 😄

https://github.com/amwmedia/node-plop
it's also up on npm 
https://www.npmjs.com/package/node-plop
