### ISSUE TITLE
Does plop support hierarchical prompts without custom prompt types?

### ISSUE THREAD

**Issue by phillipemoreira** [amwmedia/plop#71]
I believe one can use a custom prompt such as inquirer-recursive by @nathanloisel.
The suggested way for me to have hierarchical prompts would be to create a custom prompt type extending inquirejs base prompt. is that right?

**Comment by phillipemoreira** [comment]
I see it now, one can use a custom prompt such as inquirer-recursive by nathanloisel.

**Comment by amwmedia** [comment]
you can do SOME level of hierarchy using the inquirer.js [question object](https://github.com/SBoudrias/Inquirer.js/#question) `when` property. But if you need something more complex, you'd probably need a custom prompt. Unless someone else knows a better way? You could also pose this question on the inquirer repo directly.
