### ISSUE TITLE
Anyone used Plop to help generate useful git commit messages?

### ISSUE THREAD

**Issue by brandondurham** [amwmedia/plop#72]
Was considering writing a small script to help ensure our devs (including myself) always include pertinent information in their commit messages in an expected format. Has anyone used plop for something like this, as far as you know?

**Comment by amwmedia** [comment]
I have not heard of anyone do that, but it sounds very interesting! I suppose you could use a childprocess to then trigger the git commands from a custom action function. If you end up doing this, please let me know how it goes! sounds really cool :-)
