### ISSUE TITLE
Allow for alternative key/value inputs

### ISSUE THREAD

**Issue by kristianmandrup** [amwmedia/plop#73]
Would be nice to be able to pass a JSON file, JavaScript object or other alternative key/value mechanism instead of relying only on prompts

`generator.runPrompts().then(generator.runActions)` could be changed to `	generator.runInputs().then(generator.runActions)`

**Comment by kristianmandrup** [comment]
Oh, I just found [node-plop](https://github.com/amwmedia/node-plop) but not really documented.

**Comment by kristianmandrup** [comment]
Got it all working here:

- https://github.com/tecla5/plop
- https://github.com/tecla5/node-plop

**Comment by amwmedia** [comment]
yes, this is definitely possible through node-plop. Glad you were able to get this working the way you wanted ;-)

**Comment by kristianmandrup** [comment]
Well, not so straight forward. Still very much hardcoded for Terminal use. 
Had to move `doThePlop` to `node-plop` and a bunch of other tweaks, such that I could also pass the `plop` Object (inputs + actions) as an object instead of having to read from a file given a `plopFilePath`. Needs a major cleanup/refactoring for 1.0 IMO ;)

**Comment by amwmedia** [comment]
@kristianmandrup if it helps, you can actually use `node-plop` without a plopfile. You can see a basic example of this in [this ava test](https://github.com/amwmedia/node-plop/blob/master/tests/basic-no-plopfile.ava.js#L6).

**Comment by kristianmandrup** [comment]
No docs

**Comment by amwmedia** [comment]
Oh I know :-) just trying to help. Nodeplop is not really geared toward external consumption yet. When it's ready for that I'll be adding docs
