### ISSUE TITLE
Do not update to node 8.1, prompts stuck

### ISSUE THREAD

**Issue by popul** [amwmedia/plop#75]
Since i updated node to 8.1, prompts stuck forever.

Inquirer raise an issue https://github.com/nodejs/node/issues/13557

It seems to be a node issue https://github.com/SBoudrias/Inquirer.js/issues/547

With node 8.0, it works

**Comment by amwmedia** [comment]
I just verified. node 8.0 (stable) works fine, node 8.1 (latest) freezes when the user needs to enter input. Thanks for bringing this up @popul 👍

**Comment by kubal5003** [comment]
I also encountered this issue - Node 8.1 freezes, downgrade to 7.10 resolved the issue.

**Comment by styfle** [comment]
I think this is fixed in Node 8.1.1 but I haven't verified yet.

**Comment by amwmedia** [comment]
confirmed! a patch went out yesterday. 8.1.1 works for me.

**Comment by rstacruz** [comment]
I'm getting this error again in Node v8.1.2, sorry guys :(

**Comment by amwmedia** [comment]
I just tried it with node 8.1.2 and wasn't able to reproduce ☹️
