### ISSUE TITLE
Let the user to set global default values

### ISSUE THREAD

**Issue by ArielGueta** [amwmedia/plop#76]
I wonder if there is an option that the user can set up something only once. For example a path to a directory.

**Comment by amwmedia** [comment]
what kind of path? can you give me an example use case?

**Comment by ArielGueta** [comment]
For example, I want the user to be able to specify the location of the folder where the file will be created once instead of asking it each time.

**Comment by amwmedia** [comment]
if it should always be the same, wouldn't that be something that the generator should hard code? or are we talking about an instance where `user A` puts his/her files in `folder A` while `user B` puts their files in `folder B`?

**Comment by ArielGueta** [comment]
The second option.

**Comment by amwmedia** [comment]
right now you could accomplish this by putting something into package.json and using the [included `pkg` helper](https://plopjs.com/documentation/#other-helpers). does that sound like it would meet your need?

**Comment by ArielGueta** [comment]
I will check it out. It will be helpful if in the future this process will be transparent to us. Thanks a lot for this awesome library. 👍
