### ISSUE TITLE
Move plopfile into a directory other than the root

### ISSUE THREAD

**Issue by binhxn** [amwmedia/plop#77]
Hello,

I know in the Getting Started documentation the _plopfile.js_ should be kept in the root directory (namely where package.json is), but I was wondering if I can move the _plopfile.js_ to a separate directory and use the CLI to point to that specific directory to run the `plop` command. So if I moved my _plopfile.js_ in the directory `src/internal/plopfile.js`, my CLI usage would be something like `plop ./src/internal/plopfile.js`. 

Maybe I didn't read the docs fully, but I tried looking at the list of help options and couldn't find anything useful. Anything would be helpful, thanks!

**Comment by amwmedia** [comment]
I believe this might be what you're looking for.

![--plopfile property](https://www.evernote.com/l/AAF2JBfuTM1C3L0rHKaU_bDO8ZjzNDJTMqEB/image.png)

**Comment by binhxn** [comment]
That worked! What's interesting is that my list of options is completely different from yours. I even have the latest version.

![screen shot 2017-06-14 at 4 50 03 pm](https://user-images.githubusercontent.com/8155387/27159397-8fb73abe-5121-11e7-99d9-421d9f8ea56b.png)

Regardless, thanks for your help !

**Comment by amwmedia** [comment]
I'm confused, I think you just sent the help page for yarn 🤔

**Comment by binhxn** [comment]
*face palm* i did
