### ISSUE TITLE
Create an npm package from plop generator

### ISSUE THREAD

**Issue by ArielGueta** [amwmedia/plop#78]
I need some help, please. I'm trying to create an npm package generator but I don't know how to run plop through the bin key in my package.json. 

**package.json**
```
 "bin": {
   "my-gen": "index.js"
 }
```

**index.js**
```
var plop = require('plop');
plop.load('./plopfile.js');
```

But then I'm getting the error:

> load is not a function.

How can I create an npm package with plop?

**Comment by amwmedia** [comment]
is the goal to create your own command line tool that is driven behind the scenes by plop?

**Comment by amwmedia** [comment]
you could probably do that by having your command run plop from node_modules, then use the `--plopfile` command line option to target your plopfile. At that point, you can just build your plopfile like you would anywhere else. 

If you want more control you can explore using [node-plop](https://github.com/amwmedia/node-plop) which is the core library that the plop cli uses behind the scenes. You can use it [with](https://github.com/amwmedia/node-plop/blob/master/tests/basic-plopfile.ava.js#L6) or [without](https://github.com/amwmedia/node-plop/blob/master/tests/basic-no-plopfile.ava.js#L6) a separate plopfile.

**Comment by amwmedia** [comment]
node-plop is pretty robust, but I haven't taken the time to fully document it yet. If you want to go that route and have trouble getting it going, let me know. I'd be happy to help get you unstuck if needed.

**Comment by ArielGueta** [comment]
Thanks. I opened a question in SO, it would be great if you can help. I'm kind of stuck. 
https://stackoverflow.com/questions/44783673/npm-package-how-to-run-script-programmatically

**Comment by ArielGueta** [comment]
Someone suggested the following solution:
```
process.argv.push('--version');
require('plop');
```

But when I changed this to:
`process.argv.push('--plopfile ' + __dirname + '/plopfile.js');`

It's still say "No plopfile found". You have an idea, why?

**Comment by amwmedia** [comment]
change this:
`process.argv.push('--plopfile ' + __dirname + '/plopfile.js');`

to this:
`process.argv.push('--plopfile', __dirname + '/plopfile.js');`
`--------------------- comma --^`

`argv` is the already-parsed arguments, so those 2 parameters need to be separate values.

**Comment by ArielGueta** [comment]
It's working, thanks a lot for everything!

**Comment by areisle** [comment]
I tried this solution, 
```
process.argv.push('--plopfile', __dirname + '/plopfile.js');
require('plop');
```
but I couldn't seem to get it to do anything. 
does this solution still work? or is there something else I need other than those 2 lines (and a working plopfile)?

**Comment by zackkrida** [comment]
@areisle I think I'm getting the same result—no output, and plop doesn't run. Bummer :(

**Comment by areisle** [comment]
@zackkrida I ended up getting something working by using node-plop instead, but it took more like 60 lines of code vs 2. can post the code if you like; it's mostly hacked together from looking at the source code

**Comment by zackkrida** [comment]
@areisle i appreciate the follow-up! I actually rewrote my app to not depend on plop, but before that I figured out a solid way to do it. I copied what plop does in its own `bin` directory: https://github.com/plopjs/plop/blob/master/bin/plop.js

so something like this:

```js
#!/usr/bin/env node
const args = process.argv.slice(2);
const {Plop, run} = require('plop');
const argv = require('minimist')(args);

Plop.launch({
	cwd: argv.cwd,
	configPath: argv.plopfile,
	require: argv.require,
	completion: argv.completion
}, run);
```

**Comment by khus29** [comment]
@zackkrida, I used the same code to create a plugin on top of Plop, but It is giving me following error:-

`internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/...../.../node_modules/plop/src/plop.js
require() of ES modules is not supported.
require() of /Users/.../.../node_modules/plop/src/plop.js from /Users/.../../index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename plop.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/.../.../node_modules/plop/package.json.`

AM i missing anything? Please help.

**Comment by crutchcorn** [comment]
@khus29 this is because Plop 3.0 is now ESM-based. You must have your dependency also use ESM. For more, read here:
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
