### ISSUE TITLE
Enable es6 for plopfile logic without transpilation

### ISSUE THREAD

**Issue by EladBezalel** [amwmedia/plop#8]
I wanted to use plop with es6 but i couldn't,
[Liftoff](https://github.com/js-cli/js-liftoff) is exactly what you need for this project.

**Comment by kentcdodds** [comment]
Liftoff looks interesting... But it's not necessary. I just use the babel-register require hook and all my stuff can be in ES6

**Comment by amwmedia** [comment]
actually, I just looked into this a bit, and I believe it's as simple as adding --harmony to the top of the main node package. So this will be coming very soon! Thanks for raising this @EladBezalel. I'll also be looking into Liftoff and whether that would be beneficial.

**Comment by EladBezalel** [comment]
Np happy to help :+1:

**Comment by EladBezalel** [comment]
I also use babel-register, but it's just a polyfill, using liftoff will enable any compiler usage.

**Comment by EladBezalel** [comment]
(Accidentally closed :sweat_smile: )

**Comment by amwmedia** [comment]
@kentcdodds I was looking more into the babel-register require hook. Do you see any downside to just adding this to the codebase itself? I like that it uses babel, which is a little more of a known entity than the --harmony flag. any thoughts on the matter?

**Comment by kentcdodds** [comment]
I think that the best solution would be to do what gulp and webpack do. Not sure how they accomplish it, but if you have a `webpack.config.babel.js` file rather than `webpack.config.js` it'll transpile your config with babel. So you could first look for a `plopfile.babel.js` and if it's there, require the `require('babel-register')` hook perhaps?

**Comment by EladBezalel** [comment]
Gulp uses liftoff :smile:

**Comment by amwmedia** [comment]
ok, so, time to go back and look at the liftoff examples again. @EladBezalel care to submit a pull request? ;-)

**Comment by EladBezalel** [comment]
Ill do my best to assemble a proper PR as soon as i can :smile:
