### ISSUE TITLE
Dynamic / reactive prompts

### ISSUE THREAD

**Issue by adam-lynch** [amwmedia/plop#81]
Plop is handy, thanks. One thing that would top it off is the ability to tweak prompts based on previous answers. It looks like Inquirer has a ["reactive interface"](https://github.com/SBoudrias/Inquirer.js#reactive-interface) for this.

**Comment by amwmedia** [comment]
I believe support for this was just recently added to plop. Take a look at https://github.com/amwmedia/node-plop/pull/37. I believe documentation for this might have been overlooked... note to self...

**Comment by adam-lynch** [comment]
@amwmedia thanks for the quick reply. I'll leave this open to as a reminder to document it 👍

**Comment by danbopes** [comment]
This really needs better documentation.

**Comment by barth12** [comment]
Hi guys, Do you have by any chance an example of dynamic promps to share where inquirer is applied in plop? I'm struggling with that, just would like to build a flow where next question is based on the answer in previous one.

**Comment by amwmedia** [comment]
does the [inquirer example](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/examples/hierarchical.js) help at all?

I assume your use case is more complicated that what the [question object's `when()` function](https://github.com/SBoudrias/Inquirer.js/#question) would satisfy.

**Comment by barth12** [comment]
Yes, you're right. `when` is enought in my case.

**Comment by KarmaBlackshaw** [comment]
Hi! Is there a documentation for this dynamic prompt? I am depending my next prompt based on the first prompt. Like if my first prompt chooses a directory, then the second prompt will select all folders within the given directory and prompts the user with the type of list. I've done this within the actions property using `.then` but failed with  **[ERROR] Handler has no action**

**Comment by KarmaBlackshaw** [comment]
Sample code:

```
const fs = require('fs') 
const inquirer = require('inquirer')
const chalk = require('chalk')

const directories = (dir) => fs.readdirSync(dir, {
  withFileTypes: true
}).reduce((a, c) => {
  c.isDirectory() && a.push(c.name)
  return a
}, [])

const folders = directories('./src/views')

module.exports = function (plop) {
  plop.setGenerator('Handler', {
    description: 'Application translations generator',
    prompts: [
      {
        type: 'input',
        name: 'filename',
        message: 'Filename (ex. file name):'
      },
      {
        type: 'list',
        name: 'folder',
        message: 'Select folder location: ',
        choices: folders
      }
    ],
    actions: (data) => {
      const subfolders = directories(`./src/views/${data.folder}`)
      const actions = []

      inquirer.prompt({
        type: 'list',
        name: 'subfolder',
        message: 'Select subfolder location: ',
        choices: subfolders
      }).then(x => {
        actions.push({
          type: 'add',
          path: './asdfasdf.vue',
          templateFile: './generators/templates/vue.hbs',
          skipIfExists: true
        })

        return actions
      })
    }
  })
}
```

**Comment by vytis** [comment]
@KarmaBlackshaw did you manage to implement the behaviour? I am also searching to a way to have dynamic prompts, in my case I would like to re-use answer from one prompt in the next one.

**Comment by jrobber** [comment]
@vytis Not sure if you're still looking, but this turned out to be pretty simple:

1. Plop will accept this signature for prompts `async prompts(inquirer): answersObj {`;
2. Return an an object that represents the answers you want sent into the actions
3. invoke `await inquirer.prompt(prompt)` inside the function.  This accepts all standard plop/inquirer prompts and any additional ones you've registered with `setPrompt`.  This will return an object with a key that matches the `name` you provided to the prompt.

That's pretty much it.  You can now handle prompts however you want.  Because of #3 you'll have to merge all the answers onto one final object.  I created an array of prompts to iterate over.  Then if I needed a follow up question I can dynamically push or unshift it into the array and let the process continue.

Larger example:
```
config: ({
    description: 'generate a cool thing',
    async prompts(inquirer) {
        const promptQueue = [];
        const allAnswers = {};
        promptQueue.push(askQuestion1Prompt);
        while (promptQueue.length > 0) {
             const nextPrompt = promptQueue.shift();
             const nextAnswer = await inquirer.prompt(nextPrompt);
             if(someCondition){
                promptQueue.push(buildFancyPrompt(nextAnswer, allAnswers));
             }
             allAnswers = {...allAnswers, ...nextAnswer};
         }
    },
    actions: [...]
})
```

**Comment by vytis** [comment]
Thanks a lot @jrobber, this is exactly what I needed!
