### ISSUE TITLE
Send custom info to the handlebars template

### ISSUE THREAD

**Issue by richardson-trevor** [amwmedia/plop#88]
Is it possible to send custom data to the handlebars template other than by prompts? For example, in an action it'd be awesome to have a `data` attribute or similar so I could do:
```JS
{
  type: 'add',
  path: 'src/{{componentDirectory}}/index.js',
  templateFile: 'plop-templates/presentational-component.handlebars'
  data: {key1: 'value someting'}
}
```
then in the handlebars template be able to do:
```JS
{{key1}}
```
The problem we're having is that we have a single template that could be used by two different generators.  The only difference between the two usages would be an import path in a Node file. I don't want to have to prompt for the path name because that can be figured out based on which generator they chose and would thus be redundant. Appreciate any comment!

**Comment by amwmedia** [comment]
I'll give some thought to ways that we can have data injected per action. I kind of like what you've proposed. For now, you can actually use the `when` function on the [inquirer question object](https://github.com/SBoudrias/Inquirer.js/#question) to grab a reference to the answers object and mutate it yourself before it gets to the actions.

**Comment by richardson-trevor** [comment]
Excellent, I'll go that route for now and keep an eye here to see if you
decide to move in this direction. Thanks!

**Comment by mickdekkers** [comment]
Unfortunately, the `when` workaround seems to be incompatible with the bypass feature because of #95

If you have a `when` function that just modifies the data object and returns true, you'll get a
```
[ERROR] You can not bypass conditional prompts
```
message when you try to use bypass.

**Comment by amwmedia** [comment]
Thanks for the feedback, it might make sense to add a more official way to do this soon as the `when` function approach definitely feels kludgy.

**Comment by macrozone** [comment]
checkouthttps://github.com/amwmedia/node-plop/pull/59
