### ISSUE TITLE
Modify action with function

### ISSUE THREAD

**Issue by brigand** [amwmedia/plop#91]
Awesome tool! I find myself making more small files because it's less effort, and my code is better for it.

It'd be very helpful if modify accepted a function that receives the file content as a string, and in the success case it returns a string or promise of a string. In the fail case, it throws an error or returns a rejected promise.

Example use case from another issue https://github.com/amwmedia/plop/issues/33

My first use case for this is in redux adding a reducer to `combineReducers`. I can't reasonably do it with regex (different indentation levels, etc.).

This also allows future innovation, e.g. you could save the file before modification, do the modification, and ask the user if they want to revert the change.

Let me know if there's interest, and I can take a stab at it.

**Comment by amwmedia** [comment]
I think this would make a lot of sense as a third party action. I've been meaning to write a 3rd party action myself so that there could be an example repo of how they are built and consumed. If you want to take a stab at writing this, I'd be happy to help collaborate on how to write it so it's easy for other plopfiles to consume. If not, I may try to do this myself when I have time.

**Comment by brigand** [comment]
@amwmedia is there any special api for it, or the module should be a function that returns a function?

**Comment by amwmedia** [comment]
@brigand not really. There are some [api functions](https://plopjs.com/documentation/#other-methods) that you may be interested in when you're using this type of approach (like `setDefaultInclude()`), but the node module is just a standard plopfile that your package.json lists in its `main` property. I created [an example codebase](https://github.com/amwmedia/plop-pack-fancy-comments) that distributes a set of helpers, but this could just as easily include generators as well. You can also see [the link between the package.json file and the plopfile (index.js) here](https://github.com/amwmedia/plop-pack-fancy-comments/blob/master/package.json#L5).

**Comment by muco-rolle** [comment]
Hi guys I'm new to this exciting module which is making me more productive I have a question though I'm sorry in advance if it has been I tried to look in the docs I did'nt find an I'm looking for so would you provide an example of how I can you **modify action?** like I created a file and I want to import it in another file which will require to modify that file how could I achieve 

thanks again guys for this great work
