### ISSUE TITLE
CLI conditional prompts issue

### ISSUE THREAD

**Issue by zachwolf** [amwmedia/plop#95]
Hello!

Thanks for the very useful tool.

I'm having a bit of trouble and I haven't been able to find any docs about the issue. I've created [a reduced test case](https://github.com/zachwolf/plop-test/tree/master), but I'll try to break it down here as well.

I want to use the CLI to generate files. However, I also need to support conditional inputs. Plop seems to throw errors even when answering the questions. Given [these](https://github.com/zachwolf/plop-test/blob/master/generators/component/index.js#L9-L27) prompts:

```
  prompts: [{
    type: 'input',
    name: 'name',
    message: 'What should it be called?',
    default: 'Button',
  }, {
    type: 'confirm',
    name: 'hasColor',
    message: 'Do you to add a color?',
    default: false,
  }, {
    when: function (response) {
      return response.hasColor
    },
    type: 'input',
    name: 'colorValue',
    message: 'Which color would you like?',
    default: '#f311a5',
  }],
```

I would expect the following two interactions to output the exact same code:

```
$ plop --plopfile generators/index.js
? What should it be called? test
? Do you to add a color? Yes
? Which color would you like? 'red'
```

```
$ plop --plopfile generators/index.js 'test' true 'red'
```

However, I get this error:

```
[ERROR] You can not bypass conditional prompts: colorValue
```

If I remove the `when`, i.e.:

```

  prompts: [{
    type: 'input',
    name: 'name',
    message: 'What should it be called?',
    default: 'Button',
  }, {
    type: 'confirm',
    name: 'hasColor',
    message: 'Do you to add a color?',
    default: false,
  }, {
    // when: function (response) {
    //   return response.hasColor
    // },
    type: 'input',
    name: 'colorValue',
    message: 'Which color would you like?',
    default: '#f311a5',
  }],
```
It runs fine, but this greatly reduces the flexibility of what I can make. 

Is there a way for the CLI to support conditional prompts?

**Comment by amwmedia** [comment]
Hey Zach, the current way in which we accomplish the "bypass" functionality is by taking the user's input and matching it up to the prompts (in order).

We basically filter down the prompts to a new set of prompts that have NOT been answered by the user's CLI input and run those through inquirer.

If we were to support dynamic prompts, we would need to rethink the approach to use a more dynamic and interactive method of prompting. I didn't initially go through this effort because I didn't know how beneficial it would be to use bypass with complex, branching, prompts. You can still use "bypass" with generators that have conditional prompts, you are just unable to bypass THOSE prompts. You can bypass right up to them though. 

Can you tell me a little more about your use case? Are you just wanting to provide full input when running these complex generators, or are you trying to automate plop with some sort of script?

**Comment by zachwolf** [comment]
Thanks for the response. I think I understand how you're describing the underlying issue.

As for my use case, I have a React framework that I'm creating generators for. One of the generators is for a react component with options to include redux store access and a handful of other options. If a user selects to include redux store access, I want to offer the option to also create the corresponding store files. I know it's nit-picky, but it bothers me to prompt for store creation if they didn't select store access. All of these steps work great through the plop prompts. However, I want to use the CLI in order to run the generators from our CI/CD process. Doing so would allow my team to ensure that no one has broken the generators by changing file paths, an issue that has happened in the past.

This struck me as a bug since I am getting the error even when providing input to all of the commands when using the CLI. In other words, I'm not bypassing conditional prompts as the error message states. To use my post's original prompts, there should be 3 configurable options: `name`, `hasColor`, and `colorValue`. If I run the CLI command with three values (`'test' true 'red'`), my assumption was that the conditional prompt (`colorValue`) would be completed and valid.

Does that make sense?

Thanks again

**Comment by amwmedia** [comment]
if you are looking to automate the process of running plop generators, you should look at [node-plop](https://github.com/amwmedia/node-plop). This is the core logic that plop uses to do all of its work. There's no real documentation around it, but I believe your use-case is addressed by the example code you see in the readme.md file. If you have questions or issues getting it to do what you want, please feel free to log an issue.

`node-plop` will let you supply the entire answers object and bypass the prompting process altogether, and skip right to running the actions.

**Comment by zachwolf** [comment]
Awesome response, I will check out `node-plop`. Thanks for helping me out here

**Comment by dacodekid** [comment]
@amwmedia , would it make sense to add an optional new conditional check key - something like `skipWhen` - and only when - the `when` function check can be completely omitted? This might more flexibility to users. For me, I just commented out [this condition](https://github.com/plopjs/node-plop/blob/66fffd009377d83dce4b271cde285f83ee8f0c80/src/prompt-bypass.js#L128-L131) in `node-plop` and it works for my case (assuming I'm/User sending valid values for those).

```js
if (typeof p.when === 'function') {
	bypassFailures.push(`You can not bypass conditional prompts: ${p.name}`);
	bypassedPromptValues.push(false); continue;
}
```

**Comment by JSDUNIYA** [comment]
@[zachwolf](https://github.com/zachwolf)
 Did `node-plop `helped to get your issue addressed ?

**Comment by zachwolf** [comment]
@JSDUNIYA I don't remember, sorry!

**Comment by JSDUNIYA** [comment]
@zachwolf  Np, Thank you :)
