### ISSUE TITLE
Documentation: How are path names resolved?

### ISSUE THREAD

**Issue by kristianmandrup** [amwmedia/plop#96]
I'm trying to build out my generators in a structural way with subfolders for each generator etc.
How are the template paths resolved?

In short, for now I want to copy a boilerplate project structure to a destination folder, the `appName` relative to where I run my plop generator from (best practice?)

```js
import path from 'path'

const basePath = path.resolve(__dirname, '../')
const templatesPath = `${basePath}/templates`

const actions = [
  copyBoilerplate
]

const templateFiles = [
  `${templatesPath}/*`
]

const copyBoilerplate = {
  type: 'addMany',
  destination: `${appName}`,
  base: templatesPath,
  templateFiles
}
```

Is this correct? or what am I missing? 
Would be nice with some better docs on this. Are only relative paths accepted or can I use full paths like I try here? does it detect the difference and adjust automatically?
Thanks

**Comment by amwmedia** [comment]
Relative `templateFile` paths are resolved relative to the location of the `plopfile`. You are able to provide absolute paths and plop will respect those as absolute. From what you have above, it looks to me like your `destination` could be problematic. It's using an ES6 template string that would try to resolve before the prompt data came back. So if `appName` is a prompt value, I think your destination would be "undefined". Maybe I'm reading your example wrong?
