### ISSUE TITLE
Testing plop generators without polluting file system?

### ISSUE THREAD

**Issue by kristianmandrup** [amwmedia/plop#97]
Does anyone have a good recipe for how to test a plop generator!?

Trying to use [mock-fs](https://github.com/tschaub/mock-fs) with [inquirer-test](https://github.com/ewnd9/inquirer-test) so far ...

**Comment by amwmedia** [comment]
when I setup unit tests for `node-plop` I tried to get mock-fs and other similar solutions working, but I ended up just creating folders and then removing them later. I'd be interested to know if anyone else has a better approach.

**Comment by amwmedia** [comment]
@kristianmandrup were you able to have any luck with this?
