### ISSUE TITLE
plop v 1.9.0 no longer works in Node 4

### ISSUE THREAD

**Issue by benmvp** [amwmedia/plop#99]
[This commit](https://github.com/amwmedia/plop/commit/d07972ba0f6ce87545a87f84ba4224425b55254e#diff-f538aaae58c1b6494422ff25011eff65R11) in #87 adds a default parameter which isn't supported in Node 4. There may be others, but this is the error Node first hit when I tried to run `plop` in Node 4.

So I can think of two solutions:

1. We change the code to work in Node 4
2. We update the `engines` flag in [`package.json`](https://github.com/amwmedia/plop/blob/master/package.json#L39) to be a higher version of Node (most likely >= 6)

(see [node.green](http://node.green/#ES2015-syntax-default-function-parameters))

I can submit a PR for either approach, I just wanted to check in to see what was the preferred approach.

**Comment by benmvp** [comment]
By the way, the library is awesome! 🎉

**Comment by nicoespeon** [comment]
Hi @benmvp!

From my point of view − as I did this commit − I'd go for solution 1 and fix that so it still works in Node 4. That'd be easy, I just forgot about it when I used this syntax 😅

**Comment by BenAtEventbrite** [comment]
Cool. 😄  I'll submit a PR tomorrow!

**Comment by amwmedia** [comment]
agreed. Although, I will say that we'll be breaking compatibility with Node 4 soon anyway because inquirer has done so and we need to keep up to date with the latest version of our dependencies. I was planning to increment the major version at that point, so fixing this, for now, is probably the right thing to do 👍

**Comment by benmvp** [comment]
I saw with 58e3eb810e4b4e1556fb4e534b4551400197f4ff that you bumped to 1.9.1, but I'm not seeing it in NPM. Did the release actually work? https://yarnpkg.com/en/package/plop

**Comment by amwmedia** [comment]
sorry, I got pull away and didn't actually publish it to NPM. should be out there now.

**Comment by benmvp** [comment]
No worries! Just verified I could install it AND that it works in Node 4! 🎉 

Thanks again!
